// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEnWords = `-- name: CountEnWords :one
SELECT count(*)::bigint
FROM en_words
WHERE ($1::text = '' OR level_code = $1::text)
  AND ($2::text = '' OR topic = $2::text)
  AND ($3::text = '' OR status = $3::text)
`

type CountEnWordsParams struct {
	LevelCode string `json:"level_code"`
	Topic     string `json:"topic"`
	Status    string `json:"status"`
}

func (q *Queries) CountEnWords(ctx context.Context, arg CountEnWordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnWords, arg.LevelCode, arg.Topic, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countHanzi = `-- name: CountHanzi :one
SELECT count(*)::bigint
FROM hanzi
WHERE ($1::text = '' OR stage_code = $1::text)
  AND ($2::text = '' OR status = $2::text)
`

type CountHanziParams struct {
	StageCode string `json:"stage_code"`
	Status    string `json:"status"`
}

func (q *Queries) CountHanzi(ctx context.Context, arg CountHanziParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHanzi, arg.StageCode, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlanForChild = `-- name: CountPlanForChild :one
SELECT count(*)::bigint FROM curriculum_plan WHERE child_id = $1
`

func (q *Queries) CountPlanForChild(ctx context.Context, childID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlanForChild, childID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countReviewQueue = `-- name: CountReviewQueue :one
SELECT count(*)::bigint
FROM content_review r
WHERE ($1::text = '' OR r.status = $1::text)
  AND ($2::text = '' OR r.content_type = $2::text)
`

type CountReviewQueueParams struct {
	Status      string `json:"status"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CountReviewQueue(ctx context.Context, arg CountReviewQueueParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewQueue, arg.Status, arg.ContentType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStories = `-- name: CountStories :one
SELECT count(*)::bigint
FROM stories
WHERE ($1::text = '' OR lang = $1::text)
  AND ($2::text = '' OR level_code = $2::text)
  AND ($3::text = '' OR category = $3::text)
  AND ($4::text = '' OR status = $4::text)
  AND (NOT $5::boolean OR suitable)
`

type CountStoriesParams struct {
	Lang         string `json:"lang"`
	LevelCode    string `json:"level_code"`
	Category     string `json:"category"`
	Status       string `json:"status"`
	SuitableOnly bool   `json:"suitable_only"`
}

func (q *Queries) CountStories(ctx context.Context, arg CountStoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStories,
		arg.Lang,
		arg.LevelCode,
		arg.Category,
		arg.Status,
		arg.SuitableOnly,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const decideReview = `-- name: DecideReview :one
UPDATE content_review
SET status = $3, reviewer_id = $4, reviewed_at = now()
WHERE id = $1 AND status = $2
RETURNING id, content_type, ref_table, ref_id, status
`

type DecideReviewParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	Status_2   string      `json:"status_2"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
}

type DecideReviewRow struct {
	ID          uuid.UUID `json:"id"`
	ContentType string    `json:"content_type"`
	RefTable    string    `json:"ref_table"`
	RefID       uuid.UUID `json:"ref_id"`
	Status      string    `json:"status"`
}

func (q *Queries) DecideReview(ctx context.Context, arg DecideReviewParams) (DecideReviewRow, error) {
	row := q.db.QueryRow(ctx, decideReview,
		arg.ID,
		arg.Status,
		arg.Status_2,
		arg.ReviewerID,
	)
	var i DecideReviewRow
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.RefTable,
		&i.RefID,
		&i.Status,
	)
	return i, err
}

const getHanziByChar = `-- name: GetHanziByChar :one
SELECT id, "char", kp_id, pinyin, radical, stroke_count, stroke_paths, has_anim,
       explanation, stage_code, order_in_stage, source, status, created_at, updated_at
FROM hanzi
WHERE "char" = $1
`

func (q *Queries) GetHanziByChar(ctx context.Context, char string) (Hanzi, error) {
	row := q.db.QueryRow(ctx, getHanziByChar, char)
	var i Hanzi
	err := row.Scan(
		&i.ID,
		&i.Char,
		&i.KpID,
		&i.Pinyin,
		&i.Radical,
		&i.StrokeCount,
		&i.StrokePaths,
		&i.HasAnim,
		&i.Explanation,
		&i.StageCode,
		&i.OrderInStage,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHanziByID = `-- name: GetHanziByID :one
SELECT id, "char", kp_id, pinyin, radical, stroke_count, stroke_paths, has_anim,
       explanation, stage_code, order_in_stage, source, status, created_at, updated_at
FROM hanzi
WHERE id = $1
`

func (q *Queries) GetHanziByID(ctx context.Context, id uuid.UUID) (Hanzi, error) {
	row := q.db.QueryRow(ctx, getHanziByID, id)
	var i Hanzi
	err := row.Scan(
		&i.ID,
		&i.Char,
		&i.KpID,
		&i.Pinyin,
		&i.Radical,
		&i.StrokeCount,
		&i.StrokePaths,
		&i.HasAnim,
		&i.Explanation,
		&i.StageCode,
		&i.OrderInStage,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, content_type, ref_table, ref_id, title, summary, source, source_url, hits,
       status, reviewer_id, reviewed_at, created_at
FROM content_review
WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (ContentReview, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i ContentReview
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.RefTable,
		&i.RefID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.SourceUrl,
		&i.Hits,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStoryByID = `-- name: GetStoryByID :one
SELECT id, lang, title, summary, body_md, category, age_group, level_code, char_count, word_count,
       cover_url, images, new_chars, questions, discussion, unsafe_hits, suitable,
       source, source_ref, source_url, license, status, created_at, updated_at
FROM stories
WHERE id = $1
`

type GetStoryByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Lang       string             `json:"lang"`
	Title      string             `json:"title"`
	Summary    pgtype.Text        `json:"summary"`
	BodyMd     string             `json:"body_md"`
	Category   pgtype.Text        `json:"category"`
	AgeGroup   pgtype.Text        `json:"age_group"`
	LevelCode  pgtype.Text        `json:"level_code"`
	CharCount  int32              `json:"char_count"`
	WordCount  int32              `json:"word_count"`
	CoverUrl   pgtype.Text        `json:"cover_url"`
	Images     []byte             `json:"images"`
	NewChars   []byte             `json:"new_chars"`
	Questions  []byte             `json:"questions"`
	Discussion []byte             `json:"discussion"`
	UnsafeHits []byte             `json:"unsafe_hits"`
	Suitable   bool               `json:"suitable"`
	Source     string             `json:"source"`
	SourceRef  pgtype.Text        `json:"source_ref"`
	SourceUrl  pgtype.Text        `json:"source_url"`
	License    pgtype.Text        `json:"license"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetStoryByID(ctx context.Context, id uuid.UUID) (GetStoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getStoryByID, id)
	var i GetStoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Category,
		&i.AgeGroup,
		&i.LevelCode,
		&i.CharCount,
		&i.WordCount,
		&i.CoverUrl,
		&i.Images,
		&i.NewChars,
		&i.Questions,
		&i.Discussion,
		&i.UnsafeHits,
		&i.Suitable,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.License,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoryPair = `-- name: GetStoryPair :one
SELECT p.id, p.slug, p.age_group,
       p.zh_story_id, zh.title AS zh_title, zh.level_code AS zh_level_code, zh.body_md AS zh_body_md,
       p.en_story_id, en.title AS en_title, en.level_code AS en_level_code, en.body_md AS en_body_md
FROM story_pairs p
JOIN stories zh ON zh.id = p.zh_story_id
JOIN stories en ON en.id = p.en_story_id
WHERE p.zh_story_id = $1 OR p.en_story_id = $1
`

type GetStoryPairRow struct {
	ID          uuid.UUID   `json:"id"`
	Slug        string      `json:"slug"`
	AgeGroup    pgtype.Text `json:"age_group"`
	ZhStoryID   uuid.UUID   `json:"zh_story_id"`
	ZhTitle     string      `json:"zh_title"`
	ZhLevelCode pgtype.Text `json:"zh_level_code"`
	ZhBodyMd    string      `json:"zh_body_md"`
	EnStoryID   uuid.UUID   `json:"en_story_id"`
	EnTitle     string      `json:"en_title"`
	EnLevelCode pgtype.Text `json:"en_level_code"`
	EnBodyMd    string      `json:"en_body_md"`
}

func (q *Queries) GetStoryPair(ctx context.Context, zhStoryID uuid.UUID) (GetStoryPairRow, error) {
	row := q.db.QueryRow(ctx, getStoryPair, zhStoryID)
	var i GetStoryPairRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.AgeGroup,
		&i.ZhStoryID,
		&i.ZhTitle,
		&i.ZhLevelCode,
		&i.ZhBodyMd,
		&i.EnStoryID,
		&i.EnTitle,
		&i.EnLevelCode,
		&i.EnBodyMd,
	)
	return i, err
}

const insertPlanRow = `-- name: InsertPlanRow :exec
INSERT INTO curriculum_plan (child_id, kp_id, subject_code, stage_code, planned_day_index, planned_date)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (child_id, kp_id) DO NOTHING
`

type InsertPlanRowParams struct {
	ChildID         uuid.UUID   `json:"child_id"`
	KpID            uuid.UUID   `json:"kp_id"`
	SubjectCode     string      `json:"subject_code"`
	StageCode       pgtype.Text `json:"stage_code"`
	PlannedDayIndex int32       `json:"planned_day_index"`
	PlannedDate     pgtype.Date `json:"planned_date"`
}

func (q *Queries) InsertPlanRow(ctx context.Context, arg InsertPlanRowParams) error {
	_, err := q.db.Exec(ctx, insertPlanRow,
		arg.ChildID,
		arg.KpID,
		arg.SubjectCode,
		arg.StageCode,
		arg.PlannedDayIndex,
		arg.PlannedDate,
	)
	return err
}

const listChildrenForPlan = `-- name: ListChildrenForPlan :many
SELECT id, stage_code, created_at
FROM children
ORDER BY created_at
`

type ListChildrenForPlanRow struct {
	ID        uuid.UUID          `json:"id"`
	StageCode pgtype.Text        `json:"stage_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListChildrenForPlan(ctx context.Context) ([]ListChildrenForPlanRow, error) {
	rows, err := q.db.Query(ctx, listChildrenForPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildrenForPlanRow{}
	for rows.Next() {
		var i ListChildrenForPlanRow
		if err := rows.Scan(&i.ID, &i.StageCode, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnWords = `-- name: ListEnWords :many
SELECT id, word, topic, phonetic, pos, meaning_zh, definition_en, example_en, example_zh,
       frq, level_code, image_url, audio_url, status
FROM en_words
WHERE ($1::text = '' OR level_code = $1::text)
  AND ($2::text = '' OR topic = $2::text)
  AND ($3::text = '' OR status = $3::text)
ORDER BY frq, word
LIMIT $5 OFFSET $4
`

type ListEnWordsParams struct {
	LevelCode string `json:"level_code"`
	Topic     string `json:"topic"`
	Status    string `json:"status"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type ListEnWordsRow struct {
	ID           uuid.UUID   `json:"id"`
	Word         string      `json:"word"`
	Topic        pgtype.Text `json:"topic"`
	Phonetic     pgtype.Text `json:"phonetic"`
	Pos          pgtype.Text `json:"pos"`
	MeaningZh    pgtype.Text `json:"meaning_zh"`
	DefinitionEn pgtype.Text `json:"definition_en"`
	ExampleEn    pgtype.Text `json:"example_en"`
	ExampleZh    pgtype.Text `json:"example_zh"`
	Frq          int32       `json:"frq"`
	LevelCode    pgtype.Text `json:"level_code"`
	ImageUrl     pgtype.Text `json:"image_url"`
	AudioUrl     pgtype.Text `json:"audio_url"`
	Status       string      `json:"status"`
}

func (q *Queries) ListEnWords(ctx context.Context, arg ListEnWordsParams) ([]ListEnWordsRow, error) {
	rows, err := q.db.Query(ctx, listEnWords,
		arg.LevelCode,
		arg.Topic,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnWordsRow{}
	for rows.Next() {
		var i ListEnWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Topic,
			&i.Phonetic,
			&i.Pos,
			&i.MeaningZh,
			&i.DefinitionEn,
			&i.ExampleEn,
			&i.ExampleZh,
			&i.Frq,
			&i.LevelCode,
			&i.ImageUrl,
			&i.AudioUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHanzi = `-- name: ListHanzi :many
SELECT id, "char", pinyin, radical, stroke_count, has_anim, explanation,
       stage_code, order_in_stage, status
FROM hanzi
WHERE ($1::text = '' OR stage_code = $1::text)
  AND ($2::text = '' OR status = $2::text)
ORDER BY stage_code, order_in_stage, "char"
LIMIT $4 OFFSET $3
`

type ListHanziParams struct {
	StageCode string `json:"stage_code"`
	Status    string `json:"status"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type ListHanziRow struct {
	ID           uuid.UUID   `json:"id"`
	Char         string      `json:"char"`
	Pinyin       []byte      `json:"pinyin"`
	Radical      pgtype.Text `json:"radical"`
	StrokeCount  pgtype.Int2 `json:"stroke_count"`
	HasAnim      bool        `json:"has_anim"`
	Explanation  pgtype.Text `json:"explanation"`
	StageCode    pgtype.Text `json:"stage_code"`
	OrderInStage int32       `json:"order_in_stage"`
	Status       string      `json:"status"`
}

func (q *Queries) ListHanzi(ctx context.Context, arg ListHanziParams) ([]ListHanziRow, error) {
	rows, err := q.db.Query(ctx, listHanzi,
		arg.StageCode,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHanziRow{}
	for rows.Next() {
		var i ListHanziRow
		if err := rows.Scan(
			&i.ID,
			&i.Char,
			&i.Pinyin,
			&i.Radical,
			&i.StrokeCount,
			&i.HasAnim,
			&i.Explanation,
			&i.StageCode,
			&i.OrderInStage,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHanziWords = `-- name: ListHanziWords :many
SELECT id, hanzi_id, word, pinyin, sort_order, stage_ok
FROM hanzi_words
WHERE hanzi_id = ANY($1::uuid[])
ORDER BY hanzi_id, sort_order
`

type ListHanziWordsRow struct {
	ID        uuid.UUID `json:"id"`
	HanziID   uuid.UUID `json:"hanzi_id"`
	Word      string    `json:"word"`
	Pinyin    []byte    `json:"pinyin"`
	SortOrder int32     `json:"sort_order"`
	StageOk   bool      `json:"stage_ok"`
}

func (q *Queries) ListHanziWords(ctx context.Context, hanziIds []uuid.UUID) ([]ListHanziWordsRow, error) {
	rows, err := q.db.Query(ctx, listHanziWords, hanziIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHanziWordsRow{}
	for rows.Next() {
		var i ListHanziWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.HanziID,
			&i.Word,
			&i.Pinyin,
			&i.SortOrder,
			&i.StageOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedKPs = `-- name: ListPlannedKPs :many
SELECT kp.id, kp.subject_code, kp.stage_code, kp.kind, s.sort_order AS stage_order,
       COALESCE(h.order_in_stage, 0) AS order_in_stage
FROM knowledge_points kp
JOIN stages s ON s.code = kp.stage_code
LEFT JOIN hanzi h ON h.kp_id = kp.id
WHERE kp.subject_code = $1
  AND s.sort_order >= COALESCE((SELECT st.sort_order FROM stages st WHERE st.code = $2), 0)
ORDER BY s.sort_order, COALESCE(h.order_in_stage, 0), kp.code
`

type ListPlannedKPsParams struct {
	SubjectCode string `json:"subject_code"`
	Code        string `json:"code"`
}

type ListPlannedKPsRow struct {
	ID           uuid.UUID   `json:"id"`
	SubjectCode  string      `json:"subject_code"`
	StageCode    pgtype.Text `json:"stage_code"`
	Kind         string      `json:"kind"`
	StageOrder   int32       `json:"stage_order"`
	OrderInStage int32       `json:"order_in_stage"`
}

func (q *Queries) ListPlannedKPs(ctx context.Context, arg ListPlannedKPsParams) ([]ListPlannedKPsRow, error) {
	rows, err := q.db.Query(ctx, listPlannedKPs, arg.SubjectCode, arg.Code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlannedKPsRow{}
	for rows.Next() {
		var i ListPlannedKPsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectCode,
			&i.StageCode,
			&i.Kind,
			&i.StageOrder,
			&i.OrderInStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewQueue = `-- name: ListReviewQueue :many
SELECT r.id, r.content_type, r.ref_table, r.ref_id, r.title, r.summary, r.source, r.source_url,
       r.hits, r.status, r.reviewed_at, r.created_at,
       s.level_code, s.char_count, s.suitable
FROM content_review r
LEFT JOIN stories s ON s.id = r.ref_id
WHERE ($1::text = '' OR r.status = $1::text)
  AND ($2::text = '' OR r.content_type = $2::text)
ORDER BY r.created_at DESC, r.id
LIMIT $4 OFFSET $3
`

type ListReviewQueueParams struct {
	Status      string `json:"status"`
	ContentType string `json:"content_type"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

type ListReviewQueueRow struct {
	ID          uuid.UUID          `json:"id"`
	ContentType string             `json:"content_type"`
	RefTable    string             `json:"ref_table"`
	RefID       uuid.UUID          `json:"ref_id"`
	Title       pgtype.Text        `json:"title"`
	Summary     pgtype.Text        `json:"summary"`
	Source      pgtype.Text        `json:"source"`
	SourceUrl   pgtype.Text        `json:"source_url"`
	Hits        []byte             `json:"hits"`
	Status      string             `json:"status"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LevelCode   pgtype.Text        `json:"level_code"`
	CharCount   pgtype.Int4        `json:"char_count"`
	Suitable    pgtype.Bool        `json:"suitable"`
}

func (q *Queries) ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewQueue,
		arg.Status,
		arg.ContentType,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewQueueRow{}
	for rows.Next() {
		var i ListReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentType,
			&i.RefTable,
			&i.RefID,
			&i.Title,
			&i.Summary,
			&i.Source,
			&i.SourceUrl,
			&i.Hits,
			&i.Status,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.LevelCode,
			&i.CharCount,
			&i.Suitable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStages = `-- name: ListStages :many

SELECT code, subject_code, name, sort_order, target_count
FROM stages
WHERE ($1::text = '' OR subject_code = $1::text)
ORDER BY subject_code, sort_order
`

type ListStagesRow struct {
	Code        string `json:"code"`
	SubjectCode string `json:"subject_code"`
	Name        string `json:"name"`
	SortOrder   int32  `json:"sort_order"`
	TargetCount int32  `json:"target_count"`
}

// 内容模块的读查询（sqlc 生成到 internal/feature/content/dbgen）。
//
// 约定：
//  1. 列表查询一律「过滤器为空字符串即不过滤」，避免为每种组合写一条 SQL；
//  2. pinyin / stroke_paths / images 等 jsonb 列在 repository 层再解析成领域结构；
//  3. 批量导入走 internal/feature/content/bulk.go 的多行 upsert（sqlc 不做批量写）。
func (q *Queries) ListStages(ctx context.Context, subjectCode string) ([]ListStagesRow, error) {
	rows, err := q.db.Query(ctx, listStages, subjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStagesRow{}
	for rows.Next() {
		var i ListStagesRow
		if err := rows.Scan(
			&i.Code,
			&i.SubjectCode,
			&i.Name,
			&i.SortOrder,
			&i.TargetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStories = `-- name: ListStories :many
SELECT id, lang, title, summary, category, age_group, level_code, char_count, word_count,
       cover_url, suitable, status, source, source_url, created_at
FROM stories
WHERE ($1::text = '' OR lang = $1::text)
  AND ($2::text = '' OR level_code = $2::text)
  AND ($3::text = '' OR category = $3::text)
  AND ($4::text = '' OR status = $4::text)
  AND (NOT $5::boolean OR suitable)
ORDER BY level_code, title
LIMIT $7 OFFSET $6
`

type ListStoriesParams struct {
	Lang         string `json:"lang"`
	LevelCode    string `json:"level_code"`
	Category     string `json:"category"`
	Status       string `json:"status"`
	SuitableOnly bool   `json:"suitable_only"`
	Off          int32  `json:"off"`
	Lim          int32  `json:"lim"`
}

type ListStoriesRow struct {
	ID        uuid.UUID          `json:"id"`
	Lang      string             `json:"lang"`
	Title     string             `json:"title"`
	Summary   pgtype.Text        `json:"summary"`
	Category  pgtype.Text        `json:"category"`
	AgeGroup  pgtype.Text        `json:"age_group"`
	LevelCode pgtype.Text        `json:"level_code"`
	CharCount int32              `json:"char_count"`
	WordCount int32              `json:"word_count"`
	CoverUrl  pgtype.Text        `json:"cover_url"`
	Suitable  bool               `json:"suitable"`
	Status    string             `json:"status"`
	Source    string             `json:"source"`
	SourceUrl pgtype.Text        `json:"source_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListStories(ctx context.Context, arg ListStoriesParams) ([]ListStoriesRow, error) {
	rows, err := q.db.Query(ctx, listStories,
		arg.Lang,
		arg.LevelCode,
		arg.Category,
		arg.Status,
		arg.SuitableOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoriesRow{}
	for rows.Next() {
		var i ListStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Lang,
			&i.Title,
			&i.Summary,
			&i.Category,
			&i.AgeGroup,
			&i.LevelCode,
			&i.CharCount,
			&i.WordCount,
			&i.CoverUrl,
			&i.Suitable,
			&i.Status,
			&i.Source,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishStory = `-- name: PublishStory :execrows
UPDATE stories SET status = 'published', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) PublishStory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, publishStory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectStory = `-- name: RejectStory :execrows
UPDATE stories SET status = 'rejected', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) RejectStory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rejectStory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStage = `-- name: UpsertStage :exec
INSERT INTO stages (code, subject_code, name, sort_order, target_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (code) DO UPDATE SET
    subject_code = EXCLUDED.subject_code,
    name         = EXCLUDED.name,
    sort_order   = EXCLUDED.sort_order,
    target_count = EXCLUDED.target_count
`

type UpsertStageParams struct {
	Code        string `json:"code"`
	SubjectCode string `json:"subject_code"`
	Name        string `json:"name"`
	SortOrder   int32  `json:"sort_order"`
	TargetCount int32  `json:"target_count"`
}

func (q *Queries) UpsertStage(ctx context.Context, arg UpsertStageParams) error {
	_, err := q.db.Exec(ctx, upsertStage,
		arg.Code,
		arg.SubjectCode,
		arg.Name,
		arg.SortOrder,
		arg.TargetCount,
	)
	return err
}
