// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDueReviews = `-- name: CountDueReviews :one
SELECT count(*)::bigint
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.level > 0
  AND m.next_review_at <= $2
  AND ($3::text = '' OR k.subject_code = $3::text)
`

type CountDueReviewsParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	NowTs       pgtype.Timestamptz `json:"now_ts"`
	SubjectCode string             `json:"subject_code"`
}

func (q *Queries) CountDueReviews(ctx context.Context, arg CountDueReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDueReviews, arg.ChildID, arg.NowTs, arg.SubjectCode)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMastered = `-- name: CountMastered :one
SELECT count(*)::bigint
FROM mastery_records
WHERE child_id = $1 AND level >= 3
`

func (q *Queries) CountMastered(ctx context.Context, childID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMastered, childID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countWrongBook = `-- name: CountWrongBook :one
SELECT count(*)::bigint
FROM wrong_book_entries
WHERE child_id = $1
  AND (NOT $2::boolean OR cleared_at IS NULL)
`

type CountWrongBookParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	OpenOnly bool      `json:"open_only"`
}

func (q *Queries) CountWrongBook(ctx context.Context, arg CountWrongBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWrongBook, arg.ChildID, arg.OpenOnly)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM practice_assignments WHERE id = $1 AND child_id = $2
`

type DeleteAssignmentParams struct {
	ID      uuid.UUID `json:"id"`
	ChildID uuid.UUID `json:"child_id"`
}

func (q *Queries) DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteAssignment, arg.ID, arg.ChildID)
	return err
}

const deleteMastery = `-- name: DeleteMastery :exec
DELETE FROM mastery_records WHERE child_id = $1 AND kp_id = $2
`

type DeleteMasteryParams struct {
	ChildID uuid.UUID `json:"child_id"`
	KpID    uuid.UUID `json:"kp_id"`
}

func (q *Queries) DeleteMastery(ctx context.Context, arg DeleteMasteryParams) error {
	_, err := q.db.Exec(ctx, deleteMastery, arg.ChildID, arg.KpID)
	return err
}

const deleteWrongEntry = `-- name: DeleteWrongEntry :exec
DELETE FROM wrong_book_entries WHERE id = $1 AND child_id = $2
`

type DeleteWrongEntryParams struct {
	ID      uuid.UUID `json:"id"`
	ChildID uuid.UUID `json:"child_id"`
}

func (q *Queries) DeleteWrongEntry(ctx context.Context, arg DeleteWrongEntryParams) error {
	_, err := q.db.Exec(ctx, deleteWrongEntry, arg.ID, arg.ChildID)
	return err
}

const finishSession = `-- name: FinishSession :one
UPDATE learning_sessions SET
    ended_at       = $1,
    duration_sec   = $2,
    question_count = $3,
    answered_count = $4,
    correct_count  = $5,
    skipped_count  = $6,
    star_count     = $7,
    completed_by   = $8,
    status         = 'finished',
    updated_at     = now()
WHERE id = $9 AND child_id = $10 AND status = 'active'
RETURNING id, child_id, device_type, started_at, ended_at, duration_sec, question_count,
          answered_count, correct_count, skipped_count, star_count, completed_by,
          parent_score, parent_note, status
`

type FinishSessionParams struct {
	NowTs         pgtype.Timestamptz `json:"now_ts"`
	DurationSec   int32              `json:"duration_sec"`
	QuestionCount int32              `json:"question_count"`
	AnsweredCount int32              `json:"answered_count"`
	CorrectCount  int32              `json:"correct_count"`
	SkippedCount  int32              `json:"skipped_count"`
	StarCount     int32              `json:"star_count"`
	CompletedBy   pgtype.Text        `json:"completed_by"`
	ID            uuid.UUID          `json:"id"`
	ChildID       uuid.UUID          `json:"child_id"`
}

type FinishSessionRow struct {
	ID            uuid.UUID          `json:"id"`
	ChildID       uuid.UUID          `json:"child_id"`
	DeviceType    string             `json:"device_type"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	DurationSec   int32              `json:"duration_sec"`
	QuestionCount int32              `json:"question_count"`
	AnsweredCount int32              `json:"answered_count"`
	CorrectCount  int32              `json:"correct_count"`
	SkippedCount  int32              `json:"skipped_count"`
	StarCount     int32              `json:"star_count"`
	CompletedBy   pgtype.Text        `json:"completed_by"`
	ParentScore   pgtype.Int2        `json:"parent_score"`
	ParentNote    pgtype.Text        `json:"parent_note"`
	Status        string             `json:"status"`
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (FinishSessionRow, error) {
	row := q.db.QueryRow(ctx, finishSession,
		arg.NowTs,
		arg.DurationSec,
		arg.QuestionCount,
		arg.AnsweredCount,
		arg.CorrectCount,
		arg.SkippedCount,
		arg.StarCount,
		arg.CompletedBy,
		arg.ID,
		arg.ChildID,
	)
	var i FinishSessionRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.DeviceType,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.QuestionCount,
		&i.AnsweredCount,
		&i.CorrectCount,
		&i.SkippedCount,
		&i.StarCount,
		&i.CompletedBy,
		&i.ParentScore,
		&i.ParentNote,
		&i.Status,
	)
	return i, err
}

const getMastery = `-- name: GetMastery :one


SELECT id, child_id, kp_id, level, ease, interval_hours, next_review_at, difficulty,
       correct_count, wrong_count, streak, wrong_streak, last_result,
       first_learned_at, mastered_at, attempts, attempts_to_master, repeat_days, last_review_date
FROM mastery_records
WHERE child_id = $1 AND kp_id = $2
`

type GetMasteryParams struct {
	ChildID uuid.UUID `json:"child_id"`
	KpID    uuid.UUID `json:"kp_id"`
}

type GetMasteryRow struct {
	ID               uuid.UUID          `json:"id"`
	ChildID          uuid.UUID          `json:"child_id"`
	KpID             uuid.UUID          `json:"kp_id"`
	Level            int16              `json:"level"`
	Ease             float64            `json:"ease"`
	IntervalHours    float64            `json:"interval_hours"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	Difficulty       int16              `json:"difficulty"`
	CorrectCount     int32              `json:"correct_count"`
	WrongCount       int32              `json:"wrong_count"`
	Streak           int32              `json:"streak"`
	WrongStreak      int32              `json:"wrong_streak"`
	LastResult       pgtype.Text        `json:"last_result"`
	FirstLearnedAt   pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt       pgtype.Timestamptz `json:"mastered_at"`
	Attempts         int32              `json:"attempts"`
	AttemptsToMaster pgtype.Int4        `json:"attempts_to_master"`
	RepeatDays       int32              `json:"repeat_days"`
	LastReviewDate   pgtype.Date        `json:"last_review_date"`
}

// 学习域查询（sqlc 生成到 internal/dbgen）：掌握度、错题本、会话、答题流水、日汇总、专项。
//
// 约定与 content.sql 一致：列表查询「过滤器为空即不过滤」；时间一律用参数传入，
// 不在 SQL 里用 now()，方便测试与「逾期时长」排序复用同一个时间戳。
// ---------------------------------------------------------------- 掌握度
func (q *Queries) GetMastery(ctx context.Context, arg GetMasteryParams) (GetMasteryRow, error) {
	row := q.db.QueryRow(ctx, getMastery, arg.ChildID, arg.KpID)
	var i GetMasteryRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.KpID,
		&i.Level,
		&i.Ease,
		&i.IntervalHours,
		&i.NextReviewAt,
		&i.Difficulty,
		&i.CorrectCount,
		&i.WrongCount,
		&i.Streak,
		&i.WrongStreak,
		&i.LastResult,
		&i.FirstLearnedAt,
		&i.MasteredAt,
		&i.Attempts,
		&i.AttemptsToMaster,
		&i.RepeatDays,
		&i.LastReviewDate,
	)
	return i, err
}

const getMathTemplateByCode = `-- name: GetMathTemplateByCode :one
SELECT code, question_type, difficulty_band, generator_config, display_config
FROM math_templates
WHERE code = $1 AND status = 'published'
`

type GetMathTemplateByCodeRow struct {
	Code            string      `json:"code"`
	QuestionType    string      `json:"question_type"`
	DifficultyBand  pgtype.Text `json:"difficulty_band"`
	GeneratorConfig []byte      `json:"generator_config"`
	DisplayConfig   []byte      `json:"display_config"`
}

func (q *Queries) GetMathTemplateByCode(ctx context.Context, code string) (GetMathTemplateByCodeRow, error) {
	row := q.db.QueryRow(ctx, getMathTemplateByCode, code)
	var i GetMathTemplateByCodeRow
	err := row.Scan(
		&i.Code,
		&i.QuestionType,
		&i.DifficultyBand,
		&i.GeneratorConfig,
		&i.DisplayConfig,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, child_id, device_type, started_at, ended_at, duration_sec, question_count,
       answered_count, correct_count, skipped_count, star_count, completed_by,
       parent_score, parent_note, status
FROM learning_sessions
WHERE id = $1 AND child_id = $2
`

type GetSessionParams struct {
	ID      uuid.UUID `json:"id"`
	ChildID uuid.UUID `json:"child_id"`
}

type GetSessionRow struct {
	ID            uuid.UUID          `json:"id"`
	ChildID       uuid.UUID          `json:"child_id"`
	DeviceType    string             `json:"device_type"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	DurationSec   int32              `json:"duration_sec"`
	QuestionCount int32              `json:"question_count"`
	AnsweredCount int32              `json:"answered_count"`
	CorrectCount  int32              `json:"correct_count"`
	SkippedCount  int32              `json:"skipped_count"`
	StarCount     int32              `json:"star_count"`
	CompletedBy   pgtype.Text        `json:"completed_by"`
	ParentScore   pgtype.Int2        `json:"parent_score"`
	ParentNote    pgtype.Text        `json:"parent_note"`
	Status        string             `json:"status"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.ChildID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.DeviceType,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.QuestionCount,
		&i.AnsweredCount,
		&i.CorrectCount,
		&i.SkippedCount,
		&i.StarCount,
		&i.CompletedBy,
		&i.ParentScore,
		&i.ParentNote,
		&i.Status,
	)
	return i, err
}

const getSessionItem = `-- name: GetSessionItem :one
SELECT id, session_id, seq, kp_id, subject_code, stage_code, question_type, difficulty,
       question_snapshot, answer_key, state, is_correct, used_hint, elapsed_ms, answered_at
FROM session_items
WHERE id = $1 AND session_id = $2
`

type GetSessionItemParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) GetSessionItem(ctx context.Context, arg GetSessionItemParams) (SessionItem, error) {
	row := q.db.QueryRow(ctx, getSessionItem, arg.ID, arg.SessionID)
	var i SessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.KpID,
		&i.SubjectCode,
		&i.StageCode,
		&i.QuestionType,
		&i.Difficulty,
		&i.QuestionSnapshot,
		&i.AnswerKey,
		&i.State,
		&i.IsCorrect,
		&i.UsedHint,
		&i.ElapsedMs,
		&i.AnsweredAt,
	)
	return i, err
}

const getWrongEntry = `-- name: GetWrongEntry :one
SELECT id, child_id, kp_id, added_at, cleared_at, consecutive_correct, wrong_count
FROM wrong_book_entries
WHERE child_id = $1 AND kp_id = $2
`

type GetWrongEntryParams struct {
	ChildID uuid.UUID `json:"child_id"`
	KpID    uuid.UUID `json:"kp_id"`
}

type GetWrongEntryRow struct {
	ID                 uuid.UUID          `json:"id"`
	ChildID            uuid.UUID          `json:"child_id"`
	KpID               uuid.UUID          `json:"kp_id"`
	AddedAt            pgtype.Timestamptz `json:"added_at"`
	ClearedAt          pgtype.Timestamptz `json:"cleared_at"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	WrongCount         int32              `json:"wrong_count"`
}

func (q *Queries) GetWrongEntry(ctx context.Context, arg GetWrongEntryParams) (GetWrongEntryRow, error) {
	row := q.db.QueryRow(ctx, getWrongEntry, arg.ChildID, arg.KpID)
	var i GetWrongEntryRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.KpID,
		&i.AddedAt,
		&i.ClearedAt,
		&i.ConsecutiveCorrect,
		&i.WrongCount,
	)
	return i, err
}

const insertAnswerLog = `-- name: InsertAnswerLog :exec

INSERT INTO answer_logs (child_id, session_id, item_id, kp_id, subject_code, question_type,
                         is_correct, used_hint, elapsed_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAnswerLogParams struct {
	ChildID      uuid.UUID   `json:"child_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	ItemID       pgtype.UUID `json:"item_id"`
	KpID         uuid.UUID   `json:"kp_id"`
	SubjectCode  string      `json:"subject_code"`
	QuestionType string      `json:"question_type"`
	IsCorrect    bool        `json:"is_correct"`
	UsedHint     bool        `json:"used_hint"`
	ElapsedMs    int32       `json:"elapsed_ms"`
}

// ---------------------------------------------------------------- 答题流水
func (q *Queries) InsertAnswerLog(ctx context.Context, arg InsertAnswerLogParams) error {
	_, err := q.db.Exec(ctx, insertAnswerLog,
		arg.ChildID,
		arg.SessionID,
		arg.ItemID,
		arg.KpID,
		arg.SubjectCode,
		arg.QuestionType,
		arg.IsCorrect,
		arg.UsedHint,
		arg.ElapsedMs,
	)
	return err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO learning_sessions (child_id, device_type)
VALUES ($1, $2)
RETURNING id, child_id, device_type, started_at, ended_at, duration_sec, question_count,
          answered_count, correct_count, skipped_count, star_count, completed_by,
          parent_score, parent_note, status
`

type InsertSessionParams struct {
	ChildID    uuid.UUID `json:"child_id"`
	DeviceType string    `json:"device_type"`
}

type InsertSessionRow struct {
	ID            uuid.UUID          `json:"id"`
	ChildID       uuid.UUID          `json:"child_id"`
	DeviceType    string             `json:"device_type"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	DurationSec   int32              `json:"duration_sec"`
	QuestionCount int32              `json:"question_count"`
	AnsweredCount int32              `json:"answered_count"`
	CorrectCount  int32              `json:"correct_count"`
	SkippedCount  int32              `json:"skipped_count"`
	StarCount     int32              `json:"star_count"`
	CompletedBy   pgtype.Text        `json:"completed_by"`
	ParentScore   pgtype.Int2        `json:"parent_score"`
	ParentNote    pgtype.Text        `json:"parent_note"`
	Status        string             `json:"status"`
}

// ---------------------------------------------------------------- 会话
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRow(ctx, insertSession, arg.ChildID, arg.DeviceType)
	var i InsertSessionRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.DeviceType,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.QuestionCount,
		&i.AnsweredCount,
		&i.CorrectCount,
		&i.SkippedCount,
		&i.StarCount,
		&i.CompletedBy,
		&i.ParentScore,
		&i.ParentNote,
		&i.Status,
	)
	return i, err
}

const insertSessionItem = `-- name: InsertSessionItem :one
INSERT INTO session_items (session_id, seq, kp_id, subject_code, stage_code,
                           question_type, difficulty, question_snapshot, answer_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, seq, kp_id, subject_code, stage_code, question_type, difficulty,
          question_snapshot, answer_key, state, is_correct, used_hint, elapsed_ms, answered_at
`

type InsertSessionItemParams struct {
	SessionID        uuid.UUID   `json:"session_id"`
	Seq              int32       `json:"seq"`
	KpID             uuid.UUID   `json:"kp_id"`
	SubjectCode      string      `json:"subject_code"`
	StageCode        pgtype.Text `json:"stage_code"`
	QuestionType     string      `json:"question_type"`
	Difficulty       int16       `json:"difficulty"`
	QuestionSnapshot []byte      `json:"question_snapshot"`
	AnswerKey        []byte      `json:"answer_key"`
}

func (q *Queries) InsertSessionItem(ctx context.Context, arg InsertSessionItemParams) (SessionItem, error) {
	row := q.db.QueryRow(ctx, insertSessionItem,
		arg.SessionID,
		arg.Seq,
		arg.KpID,
		arg.SubjectCode,
		arg.StageCode,
		arg.QuestionType,
		arg.Difficulty,
		arg.QuestionSnapshot,
		arg.AnswerKey,
	)
	var i SessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.KpID,
		&i.SubjectCode,
		&i.StageCode,
		&i.QuestionType,
		&i.Difficulty,
		&i.QuestionSnapshot,
		&i.AnswerKey,
		&i.State,
		&i.IsCorrect,
		&i.UsedHint,
		&i.ElapsedMs,
		&i.AnsweredAt,
	)
	return i, err
}

const listDueReviews = `-- name: ListDueReviews :many
SELECT m.id, m.child_id, m.kp_id, m.level, m.ease, m.interval_hours, m.next_review_at, m.difficulty,
       m.correct_count, m.wrong_count, m.streak, m.wrong_streak, m.last_result,
       m.first_learned_at, m.mastered_at, m.attempts, m.attempts_to_master, m.repeat_days, m.last_review_date,
       k.subject_code, k.kind, k.code, k.name
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.level > 0
  AND m.next_review_at <= $2
  AND ($3::text = '' OR k.subject_code = $3::text)
ORDER BY ($2 - m.next_review_at) DESC, m.level ASC, m.kp_id
LIMIT $4
`

type ListDueReviewsParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	NowTs       pgtype.Timestamptz `json:"now_ts"`
	SubjectCode string             `json:"subject_code"`
	Lim         int32              `json:"lim"`
}

type ListDueReviewsRow struct {
	ID               uuid.UUID          `json:"id"`
	ChildID          uuid.UUID          `json:"child_id"`
	KpID             uuid.UUID          `json:"kp_id"`
	Level            int16              `json:"level"`
	Ease             float64            `json:"ease"`
	IntervalHours    float64            `json:"interval_hours"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	Difficulty       int16              `json:"difficulty"`
	CorrectCount     int32              `json:"correct_count"`
	WrongCount       int32              `json:"wrong_count"`
	Streak           int32              `json:"streak"`
	WrongStreak      int32              `json:"wrong_streak"`
	LastResult       pgtype.Text        `json:"last_result"`
	FirstLearnedAt   pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt       pgtype.Timestamptz `json:"mastered_at"`
	Attempts         int32              `json:"attempts"`
	AttemptsToMaster pgtype.Int4        `json:"attempts_to_master"`
	RepeatDays       int32              `json:"repeat_days"`
	LastReviewDate   pgtype.Date        `json:"last_review_date"`
	SubjectCode      string             `json:"subject_code"`
	Kind             string             `json:"kind"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
}

// 到期复习：逾期越久越靠前，同逾期程度下掌握度低的优先（§4.2 步骤 2）
func (q *Queries) ListDueReviews(ctx context.Context, arg ListDueReviewsParams) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews,
		arg.ChildID,
		arg.NowTs,
		arg.SubjectCode,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueReviewsRow{}
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.KpID,
			&i.Level,
			&i.Ease,
			&i.IntervalHours,
			&i.NextReviewAt,
			&i.Difficulty,
			&i.CorrectCount,
			&i.WrongCount,
			&i.Streak,
			&i.WrongStreak,
			&i.LastResult,
			&i.FirstLearnedAt,
			&i.MasteredAt,
			&i.Attempts,
			&i.AttemptsToMaster,
			&i.RepeatDays,
			&i.LastReviewDate,
			&i.SubjectCode,
			&i.Kind,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKPsByIDs = `-- name: ListKPsByIDs :many

SELECT id, subject_code, stage_code, kind, code, name, difficulty, metadata
FROM knowledge_points
WHERE id = ANY($1::uuid[])
`

type ListKPsByIDsRow struct {
	ID          uuid.UUID   `json:"id"`
	SubjectCode string      `json:"subject_code"`
	StageCode   pgtype.Text `json:"stage_code"`
	Kind        string      `json:"kind"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Difficulty  int16       `json:"difficulty"`
	Metadata    []byte      `json:"metadata"`
}

// ---------------------------------------------------------------- 组卷素材
func (q *Queries) ListKPsByIDs(ctx context.Context, kpIds []uuid.UUID) ([]ListKPsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listKPsByIDs, kpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKPsByIDsRow{}
	for rows.Next() {
		var i ListKPsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectCode,
			&i.StageCode,
			&i.Kind,
			&i.Code,
			&i.Name,
			&i.Difficulty,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasteryByKPs = `-- name: ListMasteryByKPs :many
SELECT id, child_id, kp_id, level, ease, interval_hours, next_review_at, difficulty,
       correct_count, wrong_count, streak, wrong_streak, last_result,
       first_learned_at, mastered_at, attempts, attempts_to_master, repeat_days, last_review_date
FROM mastery_records
WHERE child_id = $1 AND kp_id = ANY($2::uuid[])
`

type ListMasteryByKPsParams struct {
	ChildID uuid.UUID   `json:"child_id"`
	KpIds   []uuid.UUID `json:"kp_ids"`
}

type ListMasteryByKPsRow struct {
	ID               uuid.UUID          `json:"id"`
	ChildID          uuid.UUID          `json:"child_id"`
	KpID             uuid.UUID          `json:"kp_id"`
	Level            int16              `json:"level"`
	Ease             float64            `json:"ease"`
	IntervalHours    float64            `json:"interval_hours"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	Difficulty       int16              `json:"difficulty"`
	CorrectCount     int32              `json:"correct_count"`
	WrongCount       int32              `json:"wrong_count"`
	Streak           int32              `json:"streak"`
	WrongStreak      int32              `json:"wrong_streak"`
	LastResult       pgtype.Text        `json:"last_result"`
	FirstLearnedAt   pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt       pgtype.Timestamptz `json:"mastered_at"`
	Attempts         int32              `json:"attempts"`
	AttemptsToMaster pgtype.Int4        `json:"attempts_to_master"`
	RepeatDays       int32              `json:"repeat_days"`
	LastReviewDate   pgtype.Date        `json:"last_review_date"`
}

func (q *Queries) ListMasteryByKPs(ctx context.Context, arg ListMasteryByKPsParams) ([]ListMasteryByKPsRow, error) {
	rows, err := q.db.Query(ctx, listMasteryByKPs, arg.ChildID, arg.KpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMasteryByKPsRow{}
	for rows.Next() {
		var i ListMasteryByKPsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.KpID,
			&i.Level,
			&i.Ease,
			&i.IntervalHours,
			&i.NextReviewAt,
			&i.Difficulty,
			&i.CorrectCount,
			&i.WrongCount,
			&i.Streak,
			&i.WrongStreak,
			&i.LastResult,
			&i.FirstLearnedAt,
			&i.MasteredAt,
			&i.Attempts,
			&i.AttemptsToMaster,
			&i.RepeatDays,
			&i.LastReviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMathTemplates = `-- name: ListMathTemplates :many
SELECT code, question_type, difficulty_band, generator_config, display_config
FROM math_templates
WHERE status = 'published'
ORDER BY code
`

type ListMathTemplatesRow struct {
	Code            string      `json:"code"`
	QuestionType    string      `json:"question_type"`
	DifficultyBand  pgtype.Text `json:"difficulty_band"`
	GeneratorConfig []byte      `json:"generator_config"`
	DisplayConfig   []byte      `json:"display_config"`
}

func (q *Queries) ListMathTemplates(ctx context.Context) ([]ListMathTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listMathTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMathTemplatesRow{}
	for rows.Next() {
		var i ListMathTemplatesRow
		if err := rows.Scan(
			&i.Code,
			&i.QuestionType,
			&i.DifficultyBand,
			&i.GeneratorConfig,
			&i.DisplayConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewKPsByPlan = `-- name: ListNewKPsByPlan :many
SELECT k.id, k.subject_code, k.stage_code, k.kind, k.code, k.name, k.difficulty, k.metadata,
       p.planned_day_index
FROM curriculum_plan p
JOIN knowledge_points k ON k.id = p.kp_id
LEFT JOIN mastery_records m ON m.child_id = p.child_id AND m.kp_id = p.kp_id
WHERE p.child_id = $1
  AND p.subject_code = $2
  AND m.id IS NULL
  AND k.status = 'published'
ORDER BY p.planned_day_index, k.code
LIMIT $3
`

type ListNewKPsByPlanParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
	Lim         int32     `json:"lim"`
}

type ListNewKPsByPlanRow struct {
	ID              uuid.UUID   `json:"id"`
	SubjectCode     string      `json:"subject_code"`
	StageCode       pgtype.Text `json:"stage_code"`
	Kind            string      `json:"kind"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	Difficulty      int16       `json:"difficulty"`
	Metadata        []byte      `json:"metadata"`
	PlannedDayIndex int32       `json:"planned_day_index"`
}

// 新学候选（基准线驱动）：按标准节奏的 Day 序号取还没学过的 kp（§4.2 步骤 4）
func (q *Queries) ListNewKPsByPlan(ctx context.Context, arg ListNewKPsByPlanParams) ([]ListNewKPsByPlanRow, error) {
	rows, err := q.db.Query(ctx, listNewKPsByPlan, arg.ChildID, arg.SubjectCode, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewKPsByPlanRow{}
	for rows.Next() {
		var i ListNewKPsByPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectCode,
			&i.StageCode,
			&i.Kind,
			&i.Code,
			&i.Name,
			&i.Difficulty,
			&i.Metadata,
			&i.PlannedDayIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewKPsByStage = `-- name: ListNewKPsByStage :many
SELECT k.id, k.subject_code, k.stage_code, k.kind, k.code, k.name, k.difficulty, k.metadata,
       0::int AS planned_day_index
FROM knowledge_points k
WHERE k.subject_code = $1
  AND k.status = 'published'
  AND ($2::text = '' OR k.stage_code = $2::text)
  AND NOT EXISTS (SELECT 1 FROM mastery_records m WHERE m.child_id = $3 AND m.kp_id = k.id)
ORDER BY k.stage_code, k.difficulty, k.code
LIMIT $4
`

type ListNewKPsByStageParams struct {
	SubjectCode string    `json:"subject_code"`
	StageCode   string    `json:"stage_code"`
	ChildID     uuid.UUID `json:"child_id"`
	Lim         int32     `json:"lim"`
}

type ListNewKPsByStageRow struct {
	ID              uuid.UUID   `json:"id"`
	SubjectCode     string      `json:"subject_code"`
	StageCode       pgtype.Text `json:"stage_code"`
	Kind            string      `json:"kind"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	Difficulty      int16       `json:"difficulty"`
	Metadata        []byte      `json:"metadata"`
	PlannedDayIndex int32       `json:"planned_day_index"`
}

// 新学候选（阶段兜底）：孩子没有基准线时按阶段顺序取，保证新孩子也能开局
func (q *Queries) ListNewKPsByStage(ctx context.Context, arg ListNewKPsByStageParams) ([]ListNewKPsByStageRow, error) {
	rows, err := q.db.Query(ctx, listNewKPsByStage,
		arg.SubjectCode,
		arg.StageCode,
		arg.ChildID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewKPsByStageRow{}
	for rows.Next() {
		var i ListNewKPsByStageRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectCode,
			&i.StageCode,
			&i.Kind,
			&i.Code,
			&i.Name,
			&i.Difficulty,
			&i.Metadata,
			&i.PlannedDayIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAssignments = `-- name: ListPendingAssignments :many

SELECT a.id, a.child_id, a.kp_id, a.reason,
       k.subject_code, k.kind, k.code, k.name
FROM practice_assignments a
JOIN knowledge_points k ON k.id = a.kp_id
WHERE a.child_id = $1 AND a.status = 'pending'
ORDER BY a.created_at
LIMIT $2
`

type ListPendingAssignmentsParams struct {
	ChildID uuid.UUID `json:"child_id"`
	Lim     int32     `json:"lim"`
}

type ListPendingAssignmentsRow struct {
	ID          uuid.UUID `json:"id"`
	ChildID     uuid.UUID `json:"child_id"`
	KpID        uuid.UUID `json:"kp_id"`
	Reason      string    `json:"reason"`
	SubjectCode string    `json:"subject_code"`
	Kind        string    `json:"kind"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
}

// ---------------------------------------------------------------- 专项指派
func (q *Queries) ListPendingAssignments(ctx context.Context, arg ListPendingAssignmentsParams) ([]ListPendingAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listPendingAssignments, arg.ChildID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingAssignmentsRow{}
	for rows.Next() {
		var i ListPendingAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.KpID,
			&i.Reason,
			&i.SubjectCode,
			&i.Kind,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionItems = `-- name: ListSessionItems :many
SELECT id, session_id, seq, kp_id, subject_code, stage_code, question_type, difficulty,
       question_snapshot, answer_key, state, is_correct, used_hint, elapsed_ms, answered_at
FROM session_items
WHERE session_id = $1
ORDER BY seq
`

func (q *Queries) ListSessionItems(ctx context.Context, sessionID uuid.UUID) ([]SessionItem, error) {
	rows, err := q.db.Query(ctx, listSessionItems, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionItem{}
	for rows.Next() {
		var i SessionItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.KpID,
			&i.SubjectCode,
			&i.StageCode,
			&i.QuestionType,
			&i.Difficulty,
			&i.QuestionSnapshot,
			&i.AnswerKey,
			&i.State,
			&i.IsCorrect,
			&i.UsedHint,
			&i.ElapsedMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongBook = `-- name: ListWrongBook :many

SELECT w.id, w.child_id, w.kp_id, w.added_at, w.cleared_at, w.consecutive_correct, w.wrong_count,
       k.subject_code, k.kind, k.code, k.name
FROM wrong_book_entries w
JOIN knowledge_points k ON k.id = w.kp_id
WHERE w.child_id = $1
  AND (NOT $2::boolean OR w.cleared_at IS NULL)
ORDER BY w.cleared_at NULLS FIRST, w.added_at DESC
LIMIT $4 OFFSET $3
`

type ListWrongBookParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	OpenOnly bool      `json:"open_only"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListWrongBookRow struct {
	ID                 uuid.UUID          `json:"id"`
	ChildID            uuid.UUID          `json:"child_id"`
	KpID               uuid.UUID          `json:"kp_id"`
	AddedAt            pgtype.Timestamptz `json:"added_at"`
	ClearedAt          pgtype.Timestamptz `json:"cleared_at"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	WrongCount         int32              `json:"wrong_count"`
	SubjectCode        string             `json:"subject_code"`
	Kind               string             `json:"kind"`
	Code               string             `json:"code"`
	Name               string             `json:"name"`
}

// ---------------------------------------------------------------- 错题本
func (q *Queries) ListWrongBook(ctx context.Context, arg ListWrongBookParams) ([]ListWrongBookRow, error) {
	rows, err := q.db.Query(ctx, listWrongBook,
		arg.ChildID,
		arg.OpenOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongBookRow{}
	for rows.Next() {
		var i ListWrongBookRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.KpID,
			&i.AddedAt,
			&i.ClearedAt,
			&i.ConsecutiveCorrect,
			&i.WrongCount,
			&i.SubjectCode,
			&i.Kind,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEnWordsByKPs = `-- name: LoadEnWordsByKPs :many
SELECT k.id AS kp_id, w.id AS word_id, w.word, w.topic, w.phonetic, w.pos, w.meaning_zh,
       w.definition_en, w.example_en, w.example_zh, w.frq, w.level_code, w.image_url
FROM knowledge_points k
JOIN en_words w ON w.id = k.ref_id
WHERE k.id = ANY($1::uuid[]) AND k.kind = 'word'
`

type LoadEnWordsByKPsRow struct {
	KpID         uuid.UUID   `json:"kp_id"`
	WordID       uuid.UUID   `json:"word_id"`
	Word         string      `json:"word"`
	Topic        pgtype.Text `json:"topic"`
	Phonetic     pgtype.Text `json:"phonetic"`
	Pos          pgtype.Text `json:"pos"`
	MeaningZh    pgtype.Text `json:"meaning_zh"`
	DefinitionEn pgtype.Text `json:"definition_en"`
	ExampleEn    pgtype.Text `json:"example_en"`
	ExampleZh    pgtype.Text `json:"example_zh"`
	Frq          int32       `json:"frq"`
	LevelCode    pgtype.Text `json:"level_code"`
	ImageUrl     pgtype.Text `json:"image_url"`
}

func (q *Queries) LoadEnWordsByKPs(ctx context.Context, kpIds []uuid.UUID) ([]LoadEnWordsByKPsRow, error) {
	rows, err := q.db.Query(ctx, loadEnWordsByKPs, kpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadEnWordsByKPsRow{}
	for rows.Next() {
		var i LoadEnWordsByKPsRow
		if err := rows.Scan(
			&i.KpID,
			&i.WordID,
			&i.Word,
			&i.Topic,
			&i.Phonetic,
			&i.Pos,
			&i.MeaningZh,
			&i.DefinitionEn,
			&i.ExampleEn,
			&i.ExampleZh,
			&i.Frq,
			&i.LevelCode,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadHanziByKPs = `-- name: LoadHanziByKPs :many
SELECT k.id AS kp_id, h.id AS hanzi_id, h."char", h.pinyin, h.radical, h.stroke_count,
       h.stroke_paths, h.has_anim, h.explanation, h.stage_code, h.order_in_stage
FROM knowledge_points k
JOIN hanzi h ON h.id = k.ref_id
WHERE k.id = ANY($1::uuid[]) AND k.kind = 'hanzi'
`

type LoadHanziByKPsRow struct {
	KpID         uuid.UUID   `json:"kp_id"`
	HanziID      uuid.UUID   `json:"hanzi_id"`
	Char         string      `json:"char"`
	Pinyin       []byte      `json:"pinyin"`
	Radical      pgtype.Text `json:"radical"`
	StrokeCount  pgtype.Int2 `json:"stroke_count"`
	StrokePaths  []byte      `json:"stroke_paths"`
	HasAnim      bool        `json:"has_anim"`
	Explanation  pgtype.Text `json:"explanation"`
	StageCode    pgtype.Text `json:"stage_code"`
	OrderInStage int32       `json:"order_in_stage"`
}

func (q *Queries) LoadHanziByKPs(ctx context.Context, kpIds []uuid.UUID) ([]LoadHanziByKPsRow, error) {
	rows, err := q.db.Query(ctx, loadHanziByKPs, kpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadHanziByKPsRow{}
	for rows.Next() {
		var i LoadHanziByKPsRow
		if err := rows.Scan(
			&i.KpID,
			&i.HanziID,
			&i.Char,
			&i.Pinyin,
			&i.Radical,
			&i.StrokeCount,
			&i.StrokePaths,
			&i.HasAnim,
			&i.Explanation,
			&i.StageCode,
			&i.OrderInStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadMathTemplatesByKPs = `-- name: LoadMathTemplatesByKPs :many
SELECT k.id AS kp_id, t.code AS template_code, t.difficulty_band, t.generator_config, t.display_config
FROM knowledge_points k
JOIN math_templates t ON t.id = k.ref_id
WHERE k.id = ANY($1::uuid[]) AND k.kind = 'math_skill'
`

type LoadMathTemplatesByKPsRow struct {
	KpID            uuid.UUID   `json:"kp_id"`
	TemplateCode    string      `json:"template_code"`
	DifficultyBand  pgtype.Text `json:"difficulty_band"`
	GeneratorConfig []byte      `json:"generator_config"`
	DisplayConfig   []byte      `json:"display_config"`
}

func (q *Queries) LoadMathTemplatesByKPs(ctx context.Context, kpIds []uuid.UUID) ([]LoadMathTemplatesByKPsRow, error) {
	rows, err := q.db.Query(ctx, loadMathTemplatesByKPs, kpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadMathTemplatesByKPsRow{}
	for rows.Next() {
		var i LoadMathTemplatesByKPsRow
		if err := rows.Scan(
			&i.KpID,
			&i.TemplateCode,
			&i.DifficultyBand,
			&i.GeneratorConfig,
			&i.DisplayConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssignmentDone = `-- name: MarkAssignmentDone :exec
UPDATE practice_assignments SET status = 'done', used_at = now()
WHERE child_id = $1 AND kp_id = ANY($2::uuid[])
`

type MarkAssignmentDoneParams struct {
	ChildID uuid.UUID   `json:"child_id"`
	KpIds   []uuid.UUID `json:"kp_ids"`
}

func (q *Queries) MarkAssignmentDone(ctx context.Context, arg MarkAssignmentDoneParams) error {
	_, err := q.db.Exec(ctx, markAssignmentDone, arg.ChildID, arg.KpIds)
	return err
}

const sessionCounts = `-- name: SessionCounts :one
SELECT count(*)::bigint                                          AS total,
       count(*) FILTER (WHERE state = 'answered')::bigint        AS answered,
       count(*) FILTER (WHERE state = 'answered' AND is_correct)::bigint AS correct,
       count(*) FILTER (WHERE state = 'skipped')::bigint         AS skipped,
       count(*) FILTER (WHERE used_hint)::bigint                 AS used_hint
FROM session_items
WHERE session_id = $1
`

type SessionCountsRow struct {
	Total    int64 `json:"total"`
	Answered int64 `json:"answered"`
	Correct  int64 `json:"correct"`
	Skipped  int64 `json:"skipped"`
	UsedHint int64 `json:"used_hint"`
}

func (q *Queries) SessionCounts(ctx context.Context, sessionID uuid.UUID) (SessionCountsRow, error) {
	row := q.db.QueryRow(ctx, sessionCounts, sessionID)
	var i SessionCountsRow
	err := row.Scan(
		&i.Total,
		&i.Answered,
		&i.Correct,
		&i.Skipped,
		&i.UsedHint,
	)
	return i, err
}

const todayUsedSeconds = `-- name: TodayUsedSeconds :one
SELECT COALESCE(sum(CASE
        WHEN ended_at IS NULL THEN EXTRACT(EPOCH FROM ($1 - started_at))
        ELSE duration_sec
    END), 0)::bigint
FROM learning_sessions
WHERE child_id = $2
  AND status <> 'expired'
  AND started_at >= $3
  AND started_at < $3 + interval '1 day'
`

type TodayUsedSecondsParams struct {
	NowTs    pgtype.Timestamptz `json:"now_ts"`
	ChildID  uuid.UUID          `json:"child_id"`
	DayStart pgtype.Timestamptz `json:"day_start"`
}

// 今日已用秒数：未结束的会话按「到现在」计，保证额度校验不会因忘记 finish 而失效
func (q *Queries) TodayUsedSeconds(ctx context.Context, arg TodayUsedSecondsParams) (int64, error) {
	row := q.db.QueryRow(ctx, todayUsedSeconds, arg.NowTs, arg.ChildID, arg.DayStart)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateItemAnswer = `-- name: UpdateItemAnswer :exec
UPDATE session_items SET
    state       = $1,
    is_correct  = $2,
    used_hint   = $3,
    elapsed_ms  = $4,
    answered_at = $5
WHERE id = $6 AND session_id = $7 AND state = 'pending'
`

type UpdateItemAnswerParams struct {
	State     string             `json:"state"`
	IsCorrect pgtype.Bool        `json:"is_correct"`
	UsedHint  bool               `json:"used_hint"`
	ElapsedMs pgtype.Int4        `json:"elapsed_ms"`
	NowTs     pgtype.Timestamptz `json:"now_ts"`
	ID        uuid.UUID          `json:"id"`
	SessionID uuid.UUID          `json:"session_id"`
}

// 只认 pending → 重复提交同一题不会二次计分
func (q *Queries) UpdateItemAnswer(ctx context.Context, arg UpdateItemAnswerParams) error {
	_, err := q.db.Exec(ctx, updateItemAnswer,
		arg.State,
		arg.IsCorrect,
		arg.UsedHint,
		arg.ElapsedMs,
		arg.NowTs,
		arg.ID,
		arg.SessionID,
	)
	return err
}

const upsertAssignment = `-- name: UpsertAssignment :one
INSERT INTO practice_assignments (child_id, kp_id, parent_id, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (child_id, kp_id) DO UPDATE SET
    reason   = EXCLUDED.reason,
    status   = 'pending',
    used_at  = NULL,
    parent_id = EXCLUDED.parent_id
RETURNING id, child_id, kp_id, parent_id, reason, status, created_at
`

type UpsertAssignmentParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	KpID     uuid.UUID `json:"kp_id"`
	ParentID uuid.UUID `json:"parent_id"`
	Reason   string    `json:"reason"`
}

type UpsertAssignmentRow struct {
	ID        uuid.UUID          `json:"id"`
	ChildID   uuid.UUID          `json:"child_id"`
	KpID      uuid.UUID          `json:"kp_id"`
	ParentID  uuid.UUID          `json:"parent_id"`
	Reason    string             `json:"reason"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (UpsertAssignmentRow, error) {
	row := q.db.QueryRow(ctx, upsertAssignment,
		arg.ChildID,
		arg.KpID,
		arg.ParentID,
		arg.Reason,
	)
	var i UpsertAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.KpID,
		&i.ParentID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDailyStat = `-- name: UpsertDailyStat :one

INSERT INTO daily_stats (child_id, stat_date, subject_code, duration_sec, question_count,
                         correct_count, new_mastered, star_count, actual_new, repeat_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (child_id, stat_date, subject_code) DO UPDATE SET
    duration_sec   = daily_stats.duration_sec + EXCLUDED.duration_sec,
    question_count = daily_stats.question_count + EXCLUDED.question_count,
    correct_count  = daily_stats.correct_count + EXCLUDED.correct_count,
    new_mastered   = daily_stats.new_mastered + EXCLUDED.new_mastered,
    star_count     = daily_stats.star_count + EXCLUDED.star_count,
    actual_new     = daily_stats.actual_new + EXCLUDED.actual_new,
    repeat_count   = daily_stats.repeat_count + EXCLUDED.repeat_count,
    updated_at     = now()
RETURNING id, child_id, stat_date, subject_code, duration_sec, question_count, correct_count,
          new_mastered, star_count, planned_new, actual_new, repeat_count
`

type UpsertDailyStatParams struct {
	ChildID       uuid.UUID   `json:"child_id"`
	StatDate      pgtype.Date `json:"stat_date"`
	SubjectCode   string      `json:"subject_code"`
	DurationSec   int32       `json:"duration_sec"`
	QuestionCount int32       `json:"question_count"`
	CorrectCount  int32       `json:"correct_count"`
	NewMastered   int32       `json:"new_mastered"`
	StarCount     int32       `json:"star_count"`
	ActualNew     int32       `json:"actual_new"`
	RepeatCount   int32       `json:"repeat_count"`
}

type UpsertDailyStatRow struct {
	ID            uuid.UUID   `json:"id"`
	ChildID       uuid.UUID   `json:"child_id"`
	StatDate      pgtype.Date `json:"stat_date"`
	SubjectCode   string      `json:"subject_code"`
	DurationSec   int32       `json:"duration_sec"`
	QuestionCount int32       `json:"question_count"`
	CorrectCount  int32       `json:"correct_count"`
	NewMastered   int32       `json:"new_mastered"`
	StarCount     int32       `json:"star_count"`
	PlannedNew    int32       `json:"planned_new"`
	ActualNew     int32       `json:"actual_new"`
	RepeatCount   int32       `json:"repeat_count"`
}

// ---------------------------------------------------------------- 日汇总
// 增量累加，会话结束时调用一次（量小，不进 worker）
func (q *Queries) UpsertDailyStat(ctx context.Context, arg UpsertDailyStatParams) (UpsertDailyStatRow, error) {
	row := q.db.QueryRow(ctx, upsertDailyStat,
		arg.ChildID,
		arg.StatDate,
		arg.SubjectCode,
		arg.DurationSec,
		arg.QuestionCount,
		arg.CorrectCount,
		arg.NewMastered,
		arg.StarCount,
		arg.ActualNew,
		arg.RepeatCount,
	)
	var i UpsertDailyStatRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.StatDate,
		&i.SubjectCode,
		&i.DurationSec,
		&i.QuestionCount,
		&i.CorrectCount,
		&i.NewMastered,
		&i.StarCount,
		&i.PlannedNew,
		&i.ActualNew,
		&i.RepeatCount,
	)
	return i, err
}

const upsertMastery = `-- name: UpsertMastery :one
INSERT INTO mastery_records (child_id, kp_id, level, ease, interval_hours, next_review_at, difficulty,
                             correct_count, wrong_count, streak, wrong_streak, last_result,
                             first_learned_at, mastered_at, attempts, attempts_to_master,
                             repeat_days, last_review_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (child_id, kp_id) DO UPDATE SET
    level              = EXCLUDED.level,
    ease               = EXCLUDED.ease,
    interval_hours     = EXCLUDED.interval_hours,
    next_review_at     = EXCLUDED.next_review_at,
    difficulty         = EXCLUDED.difficulty,
    correct_count      = EXCLUDED.correct_count,
    wrong_count        = EXCLUDED.wrong_count,
    streak             = EXCLUDED.streak,
    wrong_streak       = EXCLUDED.wrong_streak,
    last_result        = EXCLUDED.last_result,
    first_learned_at   = COALESCE(mastery_records.first_learned_at, EXCLUDED.first_learned_at),
    mastered_at        = COALESCE(mastery_records.mastered_at, EXCLUDED.mastered_at),
    attempts           = EXCLUDED.attempts,
    attempts_to_master = EXCLUDED.attempts_to_master,
    repeat_days        = EXCLUDED.repeat_days,
    last_review_date   = EXCLUDED.last_review_date,
    updated_at         = now()
RETURNING id, child_id, kp_id, level, ease, interval_hours, next_review_at, difficulty,
          correct_count, wrong_count, streak, wrong_streak, last_result,
          first_learned_at, mastered_at, attempts, attempts_to_master, repeat_days, last_review_date
`

type UpsertMasteryParams struct {
	ChildID          uuid.UUID          `json:"child_id"`
	KpID             uuid.UUID          `json:"kp_id"`
	Level            int16              `json:"level"`
	Ease             float64            `json:"ease"`
	IntervalHours    float64            `json:"interval_hours"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	Difficulty       int16              `json:"difficulty"`
	CorrectCount     int32              `json:"correct_count"`
	WrongCount       int32              `json:"wrong_count"`
	Streak           int32              `json:"streak"`
	WrongStreak      int32              `json:"wrong_streak"`
	LastResult       pgtype.Text        `json:"last_result"`
	FirstLearnedAt   pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt       pgtype.Timestamptz `json:"mastered_at"`
	Attempts         int32              `json:"attempts"`
	AttemptsToMaster pgtype.Int4        `json:"attempts_to_master"`
	RepeatDays       int32              `json:"repeat_days"`
	LastReviewDate   pgtype.Date        `json:"last_review_date"`
}

type UpsertMasteryRow struct {
	ID               uuid.UUID          `json:"id"`
	ChildID          uuid.UUID          `json:"child_id"`
	KpID             uuid.UUID          `json:"kp_id"`
	Level            int16              `json:"level"`
	Ease             float64            `json:"ease"`
	IntervalHours    float64            `json:"interval_hours"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	Difficulty       int16              `json:"difficulty"`
	CorrectCount     int32              `json:"correct_count"`
	WrongCount       int32              `json:"wrong_count"`
	Streak           int32              `json:"streak"`
	WrongStreak      int32              `json:"wrong_streak"`
	LastResult       pgtype.Text        `json:"last_result"`
	FirstLearnedAt   pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt       pgtype.Timestamptz `json:"mastered_at"`
	Attempts         int32              `json:"attempts"`
	AttemptsToMaster pgtype.Int4        `json:"attempts_to_master"`
	RepeatDays       int32              `json:"repeat_days"`
	LastReviewDate   pgtype.Date        `json:"last_review_date"`
}

func (q *Queries) UpsertMastery(ctx context.Context, arg UpsertMasteryParams) (UpsertMasteryRow, error) {
	row := q.db.QueryRow(ctx, upsertMastery,
		arg.ChildID,
		arg.KpID,
		arg.Level,
		arg.Ease,
		arg.IntervalHours,
		arg.NextReviewAt,
		arg.Difficulty,
		arg.CorrectCount,
		arg.WrongCount,
		arg.Streak,
		arg.WrongStreak,
		arg.LastResult,
		arg.FirstLearnedAt,
		arg.MasteredAt,
		arg.Attempts,
		arg.AttemptsToMaster,
		arg.RepeatDays,
		arg.LastReviewDate,
	)
	var i UpsertMasteryRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.KpID,
		&i.Level,
		&i.Ease,
		&i.IntervalHours,
		&i.NextReviewAt,
		&i.Difficulty,
		&i.CorrectCount,
		&i.WrongCount,
		&i.Streak,
		&i.WrongStreak,
		&i.LastResult,
		&i.FirstLearnedAt,
		&i.MasteredAt,
		&i.Attempts,
		&i.AttemptsToMaster,
		&i.RepeatDays,
		&i.LastReviewDate,
	)
	return i, err
}

const upsertWrongEntry = `-- name: UpsertWrongEntry :one
INSERT INTO wrong_book_entries (child_id, kp_id, cleared_at, consecutive_correct, wrong_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (child_id, kp_id) DO UPDATE SET
    cleared_at          = EXCLUDED.cleared_at,
    consecutive_correct = EXCLUDED.consecutive_correct,
    wrong_count         = wrong_book_entries.wrong_count + 1,
    updated_at          = now()
RETURNING id, child_id, kp_id, added_at, cleared_at, consecutive_correct, wrong_count
`

type UpsertWrongEntryParams struct {
	ChildID            uuid.UUID          `json:"child_id"`
	KpID               uuid.UUID          `json:"kp_id"`
	ClearedAt          pgtype.Timestamptz `json:"cleared_at"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	WrongCount         int32              `json:"wrong_count"`
}

type UpsertWrongEntryRow struct {
	ID                 uuid.UUID          `json:"id"`
	ChildID            uuid.UUID          `json:"child_id"`
	KpID               uuid.UUID          `json:"kp_id"`
	AddedAt            pgtype.Timestamptz `json:"added_at"`
	ClearedAt          pgtype.Timestamptz `json:"cleared_at"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	WrongCount         int32              `json:"wrong_count"`
}

func (q *Queries) UpsertWrongEntry(ctx context.Context, arg UpsertWrongEntryParams) (UpsertWrongEntryRow, error) {
	row := q.db.QueryRow(ctx, upsertWrongEntry,
		arg.ChildID,
		arg.KpID,
		arg.ClearedAt,
		arg.ConsecutiveCorrect,
		arg.WrongCount,
	)
	var i UpsertWrongEntryRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.KpID,
		&i.AddedAt,
		&i.ClearedAt,
		&i.ConsecutiveCorrect,
		&i.WrongCount,
	)
	return i, err
}
