// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// 原始答题流水，日汇总的原料。按决策 #6 不分区
type AnswerLog struct {
	ID           int64              `json:"id"`
	ChildID      uuid.UUID          `json:"child_id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	ItemID       pgtype.UUID        `json:"item_id"`
	KpID         uuid.UUID          `json:"kp_id"`
	SubjectCode  string             `json:"subject_code"`
	QuestionType string             `json:"question_type"`
	IsCorrect    bool               `json:"is_correct"`
	UsedHint     bool               `json:"used_hint"`
	ElapsedMs    int32              `json:"elapsed_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// 孩子档案：一个家长独占自己的孩子，不跨家长共享
type Child struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
	Nickname string    `json:"nickname"`
	AvatarID string    `json:"avatar_id"`
	// 只保留年月（YYYYMM），符合儿童隐私最小化要求
	BirthYm   pgtype.Text        `json:"birth_ym"`
	StageCode pgtype.Text        `json:"stage_code"`
	Active    bool               `json:"active"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 审核队列：采集/导入内容默认进队，家长通过后目标表转 published
type ContentReview struct {
	ID          uuid.UUID          `json:"id"`
	ContentType string             `json:"content_type"`
	RefTable    string             `json:"ref_table"`
	RefID       uuid.UUID          `json:"ref_id"`
	Title       pgtype.Text        `json:"title"`
	Summary     pgtype.Text        `json:"summary"`
	Source      pgtype.Text        `json:"source"`
	SourceUrl   pgtype.Text        `json:"source_url"`
	Hits        []byte             `json:"hits"`
	Status      string             `json:"status"`
	ReviewerID  pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 标准节奏基准线：语文 6 字/天、英语 5 词/天铺 Day 1..N，只作参照不设闸门
type CurriculumPlan struct {
	ID              uuid.UUID   `json:"id"`
	ChildID         uuid.UUID   `json:"child_id"`
	KpID            uuid.UUID   `json:"kp_id"`
	SubjectCode     string      `json:"subject_code"`
	StageCode       pgtype.Text `json:"stage_code"`
	PlannedDayIndex int32       `json:"planned_day_index"`
	// 按标准节奏推算的计划日期，与实际进度相减即偏差天数
	PlannedDate pgtype.Date        `json:"planned_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 日汇总：会话结束时同步增量更新（量小）；planned/cum/deviation 三列留待 M4 报表与节奏偏差
type DailyStat struct {
	ID            uuid.UUID   `json:"id"`
	ChildID       uuid.UUID   `json:"child_id"`
	StatDate      pgtype.Date `json:"stat_date"`
	SubjectCode   string      `json:"subject_code"`
	DurationSec   int32       `json:"duration_sec"`
	QuestionCount int32       `json:"question_count"`
	CorrectCount  int32       `json:"correct_count"`
	NewMastered   int32       `json:"new_mastered"`
	StarCount     int32       `json:"star_count"`
	PlannedNew    int32       `json:"planned_new"`
	ActualNew     int32       `json:"actual_new"`
	RepeatCount   int32       `json:"repeat_count"`
	CumPlanned    int32       `json:"cum_planned"`
	CumActual     int32       `json:"cum_actual"`
	// 正 = 落后标准节奏 N 天，负 = 提前
	DeviationDays float64            `json:"deviation_days"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// 英语句型库：E10 的 ~130 句句型，M3 起用于句型填空与跟读
type EnSentence struct {
	ID          uuid.UUID          `json:"id"`
	KpID        pgtype.UUID        `json:"kp_id"`
	Text        string             `json:"text"`
	Translation pgtype.Text        `json:"translation"`
	LevelCode   pgtype.Text        `json:"level_code"`
	AudioUrl    pgtype.Text        `json:"audio_url"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 英语单词：ECDICT 释义 + 自有词频分级 + E1-E10 级别（frq 越小越常用）
type EnWord struct {
	ID           uuid.UUID   `json:"id"`
	KpID         pgtype.UUID `json:"kp_id"`
	Word         string      `json:"word"`
	Topic        pgtype.Text `json:"topic"`
	Phonetic     pgtype.Text `json:"phonetic"`
	Pos          pgtype.Text `json:"pos"`
	MeaningZh    pgtype.Text `json:"meaning_zh"`
	DefinitionEn pgtype.Text `json:"definition_en"`
	ExampleEn    pgtype.Text `json:"example_en"`
	ExampleZh    pgtype.Text `json:"example_zh"`
	// COCA 词频序号，升序即越常用；缺失记 0
	Frq       int32              `json:"frq"`
	LevelCode pgtype.Text        `json:"level_code"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	AudioUrl  pgtype.Text        `json:"audio_url"`
	Source    string             `json:"source"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 汉字字典：拼音/部首/笔画/笔顺（hanzi-writer 原始 JSON）/所属阶段
type Hanzi struct {
	ID          uuid.UUID   `json:"id"`
	Char        string      `json:"char"`
	KpID        pgtype.UUID `json:"kp_id"`
	Pinyin      []byte      `json:"pinyin"`
	Radical     pgtype.Text `json:"radical"`
	StrokeCount pgtype.Int2 `json:"stroke_count"`
	// hanzi-writer 字形数据（strokes + medians），为空表示缺字形，前端退回静态字图
	StrokePaths []byte      `json:"stroke_paths"`
	HasAnim     bool        `json:"has_anim"`
	Explanation pgtype.Text `json:"explanation"`
	StageCode   pgtype.Text `json:"stage_code"`
	// 阶段内顺序，决定新学顺序与 curriculum_plan 铺线顺序
	OrderInStage int32              `json:"order_in_stage"`
	Source       string             `json:"source"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 控字组词：每字 6 条，只用已学阶段的字；stage_ok 由家长复核后置位
type HanziWord struct {
	ID        uuid.UUID          `json:"id"`
	HanziID   uuid.UUID          `json:"hanzi_id"`
	Word      string             `json:"word"`
	Pinyin    []byte             `json:"pinyin"`
	SortOrder int32              `json:"sort_order"`
	StageOk   bool               `json:"stage_ok"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 掌握度挂载点：每个汉字/单词/题型档/故事一条，SM-2 状态机只认这张表
type KnowledgePoint struct {
	ID          uuid.UUID   `json:"id"`
	SubjectCode string      `json:"subject_code"`
	StageCode   pgtype.Text `json:"stage_code"`
	Kind        string      `json:"kind"`
	// 指向 hanzi/en_words/stories 等表，跨表故不加外键
	RefID pgtype.UUID `json:"ref_id"`
	// 稳定业务码（hanzi:一 / word:cat），重跑导入按同一码去重
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	Difficulty int16              `json:"difficulty"`
	Metadata   []byte             `json:"metadata"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// 一次学习 = 一个会话；家长可补录主观评价（parent_score），不计入客观正确率
type LearningSession struct {
	ID            uuid.UUID          `json:"id"`
	ChildID       uuid.UUID          `json:"child_id"`
	DeviceType    string             `json:"device_type"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	DurationSec   int32              `json:"duration_sec"`
	QuestionCount int32              `json:"question_count"`
	AnsweredCount int32              `json:"answered_count"`
	CorrectCount  int32              `json:"correct_count"`
	SkippedCount  int32              `json:"skipped_count"`
	StarCount     int32              `json:"star_count"`
	// auto 程序判定 / parent 家长确认或补录 / mixed 两者皆有
	CompletedBy pgtype.Text        `json:"completed_by"`
	ParentScore pgtype.Int2        `json:"parent_score"`
	ParentNote  pgtype.Text        `json:"parent_note"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// 登录审计：记录登录/扫码/兑换等事件，便于排查异常登录
type LoginAudit struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Event     string             `json:"event"`
	Ip        *netip.Addr        `json:"ip"`
	Ua        pgtype.Text        `json:"ua"`
	Success   bool               `json:"success"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 掌握度唯一挂载点：每个（孩子, 知识点）一条，简化 SM-2 的状态全在这里
type MasteryRecord struct {
	ID      uuid.UUID `json:"id"`
	ChildID uuid.UUID `json:"child_id"`
	KpID    uuid.UUID `json:"kp_id"`
	// 0 未学 / 1-2 学习中 / 3 已掌握 / 4-5 巩固与维持
	Level int16   `json:"level"`
	Ease  float64 `json:"ease"`
	// 下次复习间隔（小时）。0.17 表示 10 分钟后会话内复现
	IntervalHours float64            `json:"interval_hours"`
	NextReviewAt  pgtype.Timestamptz `json:"next_review_at"`
	// 难度档，由难度自适应升降（§4.2：连 3 次正确率<60% 降档）
	Difficulty     int16              `json:"difficulty"`
	CorrectCount   int32              `json:"correct_count"`
	WrongCount     int32              `json:"wrong_count"`
	Streak         int32              `json:"streak"`
	WrongStreak    int32              `json:"wrong_streak"`
	LastResult     pgtype.Text        `json:"last_result"`
	FirstLearnedAt pgtype.Timestamptz `json:"first_learned_at"`
	MasteredAt     pgtype.Timestamptz `json:"mastered_at"`
	Attempts       int32              `json:"attempts"`
	// 掌握前花了多少次作答；与 attempts 相除即学习效率
	AttemptsToMaster pgtype.Int4 `json:"attempts_to_master"`
	// 出现在多少个不同学习日，用于统计「标准内容的重复次数」
	RepeatDays     int32              `json:"repeat_days"`
	LastReviewDate pgtype.Date        `json:"last_review_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// 数学题模板：模板 + 参数化生成（seed 可复现），M3 起启用
type MathTemplate struct {
	ID              uuid.UUID          `json:"id"`
	Code            string             `json:"code"`
	QuestionType    string             `json:"question_type"`
	DifficultyBand  pgtype.Text        `json:"difficulty_band"`
	GeneratorConfig []byte             `json:"generator_config"`
	DisplayConfig   []byte             `json:"display_config"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// 家长账号：邮箱与手机号至少其一；密码 bcrypt，PIN 用于二次校验
type Parent struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	PinHash      pgtype.Text        `json:"pin_hash"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 家长控制：时长、休息间隔、学科开关、护眼主题与节奏基准模式
type ParentSetting struct {
	ParentID             uuid.UUID          `json:"parent_id"`
	DailyLimitMin        int32              `json:"daily_limit_min"`
	SessionLimitMin      int32              `json:"session_limit_min"`
	AllowedWindow        []byte             `json:"allowed_window"`
	RestIntervalMin      int32              `json:"rest_interval_min"`
	SubjectSwitches      []byte             `json:"subject_switches"`
	Theme                string             `json:"theme"`
	FontScale            string             `json:"font_scale"`
	LowBlueLight         bool               `json:"low_blue_light"`
	RequireParentConfirm bool               `json:"require_parent_confirm"`
	PaceMode             string             `json:"pace_mode"`
	CompareChildren      bool               `json:"compare_children"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// 家长专项指派：来自报表建议或打印补录，优先进入今日任务（§4.2 步骤 5）
type PracticeAssignment struct {
	ID        uuid.UUID          `json:"id"`
	ChildID   uuid.UUID          `json:"child_id"`
	KpID      uuid.UUID          `json:"kp_id"`
	ParentID  uuid.UUID          `json:"parent_id"`
	Reason    string             `json:"reason"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

// 扫码登录会话：二维码 60 秒过期，兑换码一次性
type QrLoginSession struct {
	ID               uuid.UUID          `json:"id"`
	QrToken          string             `json:"qr_token"`
	Status           string             `json:"status"`
	CreatorIp        *netip.Addr        `json:"creator_ip"`
	CreatorUa        pgtype.Text        `json:"creator_ua"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	ScanCount        int32              `json:"scan_count"`
	ExchangeCodeHash pgtype.Text        `json:"exchange_code_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	// 确认后签发的一次性兑换码截止时间（30 秒）
	ExchangeExpiresAt pgtype.Timestamptz `json:"exchange_expires_at"`
	// 兑换失败次数，累计 5 次置 failed 防暴力尝试
	FailedCount int32 `json:"failed_count"`
}

// 刷新令牌：30 天有效，轮换时由 replaced_by 指认后继，支持服务端撤销
type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	ParentID   uuid.UUID          `json:"parent_id"`
	TokenHash  string             `json:"token_hash"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// 题目快照：答题即落库，报表可复现，不依赖题库后续变更
type SessionItem struct {
	ID           uuid.UUID   `json:"id"`
	SessionID    uuid.UUID   `json:"session_id"`
	Seq          int32       `json:"seq"`
	KpID         uuid.UUID   `json:"kp_id"`
	SubjectCode  string      `json:"subject_code"`
	StageCode    pgtype.Text `json:"stage_code"`
	QuestionType string      `json:"question_type"`
	Difficulty   int16       `json:"difficulty"`
	// 题面（prompt/options/media），可直接下发给前端
	QuestionSnapshot []byte `json:"question_snapshot"`
	// 正确答案，服务端判分专用，任何读接口都不返回
	AnswerKey []byte `json:"answer_key"`
	State     string `json:"state"`
	// NULL = 未判定（trace/say 等主观项），不计入客观正确率
	IsCorrect  pgtype.Bool        `json:"is_correct"`
	UsedHint   bool               `json:"used_hint"`
	ElapsedMs  pgtype.Int4        `json:"elapsed_ms"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

// 学习阶段基准：S0-S5 / G1-G12 / X1-X6（语文），E1-E10（英语），L1-L5（数学）
type Stage struct {
	Code        string             `json:"code"`
	SubjectCode string             `json:"subject_code"`
	Name        string             `json:"name"`
	SortOrder   int32              `json:"sort_order"`
	TargetCount int32              `json:"target_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 故事：中文 17,250（采集）+ 中英双语 1,663；默认 pending，需家长过审核队列
type Story struct {
	ID         uuid.UUID   `json:"id"`
	Lang       string      `json:"lang"`
	Title      string      `json:"title"`
	Summary    pgtype.Text `json:"summary"`
	BodyMd     string      `json:"body_md"`
	Category   pgtype.Text `json:"category"`
	AgeGroup   pgtype.Text `json:"age_group"`
	LevelCode  pgtype.Text `json:"level_code"`
	CharCount  int32       `json:"char_count"`
	WordCount  int32       `json:"word_count"`
	CoverUrl   pgtype.Text `json:"cover_url"`
	Images     []byte      `json:"images"`
	NewChars   []byte      `json:"new_chars"`
	Questions  []byte      `json:"questions"`
	Discussion []byte      `json:"discussion"`
	UnsafeHits []byte      `json:"unsafe_hits"`
	// 适宜性筛查结果：命中不宜词库为 false，孩子端默认屏蔽，家长可逐条解除
	Suitable bool `json:"suitable"`
	// 正文 SHA-256，导入幂等键
	ContentHash string             `json:"content_hash"`
	Source      string             `json:"source"`
	SourceRef   pgtype.Text        `json:"source_ref"`
	SourceUrl   pgtype.Text        `json:"source_url"`
	License     pgtype.Text        `json:"license"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// 双语配对：中英一一对应，支撑中/英/对照三种阅读模式
type StoryPair struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	ZhStoryID uuid.UUID          `json:"zh_story_id"`
	EnStoryID uuid.UUID          `json:"en_story_id"`
	AgeGroup  pgtype.Text        `json:"age_group"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 学科字典：chinese / math / english
type Subject struct {
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 视频白名单：只存元数据，不下载；孩子端仅家长添加过的可见
type Video struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	SourceType  string             `json:"source_type"`
	Bvid        pgtype.Text        `json:"bvid"`
	SourceUrl   string             `json:"source_url"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	LevelCode   pgtype.Text        `json:"level_code"`
	CoverUrl    pgtype.Text        `json:"cover_url"`
	SubtitleUrl pgtype.Text        `json:"subtitle_url"`
	AddedBy     pgtype.UUID        `json:"added_by"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 错题本：同一 kp 只保留一条，答错重新打开（cleared_at 置空），连对 3 次自动移出
type WrongBookEntry struct {
	ID      uuid.UUID          `json:"id"`
	ChildID uuid.UUID          `json:"child_id"`
	KpID    uuid.UUID          `json:"kp_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	// NULL = 在错题中；非 NULL = 已移出（保留记录供统计）
	ClearedAt          pgtype.Timestamptz `json:"cleared_at"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	WrongCount         int32              `json:"wrong_count"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
