// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: print.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPrintJobs = `-- name: ClaimPrintJobs :many
WITH claimed AS (
    SELECT id FROM print_jobs
    WHERE status = 'queued'
    ORDER BY created_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE print_jobs p SET status = 'rendering', updated_at = now()
FROM claimed c
WHERE p.id = c.id
RETURNING p.id, p.child_id, p.template_code, p.payload, p.page_count
`

type ClaimPrintJobsRow struct {
	ID           uuid.UUID `json:"id"`
	ChildID      uuid.UUID `json:"child_id"`
	TemplateCode string    `json:"template_code"`
	Payload      []byte    `json:"payload"`
	PageCount    int32     `json:"page_count"`
}

// worker 拉取待渲染任务（多实例安全）。
func (q *Queries) ClaimPrintJobs(ctx context.Context, lim int32) ([]ClaimPrintJobsRow, error) {
	rows, err := q.db.Query(ctx, claimPrintJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPrintJobsRow{}
	for rows.Next() {
		var i ClaimPrintJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TemplateCode,
			&i.Payload,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPrintJobPDF = `-- name: ClearPrintJobPDF :exec
UPDATE print_jobs SET
    pdf_path      = NULL,
    page_count    = 0,
    status        = 'created',
    error_message = '',
    updated_at    = now()
WHERE id = $1
`

func (q *Queries) ClearPrintJobPDF(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrintJobPDF, id)
	return err
}

const countPrintJobs = `-- name: CountPrintJobs :one
SELECT count(*)::bigint AS total
FROM print_jobs
WHERE parent_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid
       OR child_id = $2::uuid)
`

type CountPrintJobsParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ChildID  uuid.UUID `json:"child_id"`
}

func (q *Queries) CountPrintJobs(ctx context.Context, arg CountPrintJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrintJobs, arg.ParentID, arg.ChildID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPrintJob = `-- name: CreatePrintJob :one


INSERT INTO print_jobs (parent_id, child_id, template_code, params, payload, page_count)
VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    $5::jsonb,
    $6
)
RETURNING id, parent_id, child_id, template_code, params, payload, page_count,
          pdf_path, status, error_message, marked_done_at, created_at, updated_at
`

type CreatePrintJobParams struct {
	ParentID     uuid.UUID `json:"parent_id"`
	ChildID      uuid.UUID `json:"child_id"`
	TemplateCode string    `json:"template_code"`
	Params       []byte    `json:"params"`
	Payload      []byte    `json:"payload"`
	PageCount    int32     `json:"page_count"`
}

// 打印中心的查询（§4.6）。
//
// 约定：
//  1. payload 是自洽的数据快照：worker 渲染 PDF 时只依赖它 + template_code，
//     不再回查 content/mastery —— 否则模板改版或内容下线会让历史任务渲染不出原样。
//  2. 「无过滤」用哨兵值表示（child_id = 全零 uuid），与 content.sql 用 ” 表示无过滤一致，
//     避免 sqlc 在可空参数上的类型推断歧义。
//  3. worker 取任务用 FOR UPDATE SKIP LOCKED，多实例并行拉取不会重复渲染同一个 job。
//
// ---------------------------------------------------------------- 建与读
func (q *Queries) CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, createPrintJob,
		arg.ParentID,
		arg.ChildID,
		arg.TemplateCode,
		arg.Params,
		arg.Payload,
		arg.PageCount,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Params,
		&i.Payload,
		&i.PageCount,
		&i.PdfPath,
		&i.Status,
		&i.ErrorMessage,
		&i.MarkedDoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrintJob = `-- name: GetPrintJob :one
SELECT id, parent_id, child_id, template_code, params, payload, page_count,
       pdf_path, status, error_message, marked_done_at, created_at, updated_at
FROM print_jobs
WHERE id = $1 AND parent_id = $2
`

type GetPrintJobParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

func (q *Queries) GetPrintJob(ctx context.Context, arg GetPrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, getPrintJob, arg.ID, arg.ParentID)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Params,
		&i.Payload,
		&i.PageCount,
		&i.PdfPath,
		&i.Status,
		&i.ErrorMessage,
		&i.MarkedDoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrintSession = `-- name: InsertPrintSession :one
INSERT INTO learning_sessions (
    child_id, device_type, started_at, ended_at, question_count, answered_count,
    correct_count, star_count, completed_by, parent_note, status, print_job_id
)
VALUES (
    $1, 'print', now(), now(),
    $2, $3, $4,
    0, 'parent', $5, 'finished', $6
)
RETURNING id
`

type InsertPrintSessionParams struct {
	ChildID       uuid.UUID   `json:"child_id"`
	QuestionCount int32       `json:"question_count"`
	AnsweredCount int32       `json:"answered_count"`
	CorrectCount  int32       `json:"correct_count"`
	ParentNote    pgtype.Text `json:"parent_note"`
	PrintJobID    pgtype.UUID `json:"print_job_id"`
}

// 补录产生的学习会话：completed_by='parent'，并回指到 print_job，报表可区分来源（§4.11）。
func (q *Queries) InsertPrintSession(ctx context.Context, arg InsertPrintSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPrintSession,
		arg.ChildID,
		arg.QuestionCount,
		arg.AnsweredCount,
		arg.CorrectCount,
		arg.ParentNote,
		arg.PrintJobID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listExpiredPrintJobs = `-- name: ListExpiredPrintJobs :many

SELECT id, pdf_path
FROM print_jobs
WHERE pdf_path IS NOT NULL AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListExpiredPrintJobsParams struct {
	Before pgtype.Timestamptz `json:"before"`
	Lim    int32              `json:"lim"`
}

type ListExpiredPrintJobsRow struct {
	ID      uuid.UUID   `json:"id"`
	PdfPath pgtype.Text `json:"pdf_path"`
}

// ---------------------------------------------------------------- 保留期清理
// 超过保留期、PDF 还在的任务。payload 是不可变快照，清掉 PDF 后随时能重新渲染，
// 所以清理只删文件、不动打印记录本身（家长还能看到「当时印过什么」）。
func (q *Queries) ListExpiredPrintJobs(ctx context.Context, arg ListExpiredPrintJobsParams) ([]ListExpiredPrintJobsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPrintJobs, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredPrintJobsRow{}
	for rows.Next() {
		var i ListExpiredPrintJobsRow
		if err := rows.Scan(&i.ID, &i.PdfPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobs = `-- name: ListPrintJobs :many
SELECT id, parent_id, child_id, template_code, params, payload, page_count,
       pdf_path, status, error_message, marked_done_at, created_at, updated_at
FROM print_jobs
WHERE parent_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid
       OR child_id = $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListPrintJobsParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ChildID  uuid.UUID `json:"child_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListPrintJobs(ctx context.Context, arg ListPrintJobsParams) ([]PrintJob, error) {
	rows, err := q.db.Query(ctx, listPrintJobs,
		arg.ParentID,
		arg.ChildID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ChildID,
			&i.TemplateCode,
			&i.Params,
			&i.Payload,
			&i.PageCount,
			&i.PdfPath,
			&i.Status,
			&i.ErrorMessage,
			&i.MarkedDoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPrintJobDone = `-- name: MarkPrintJobDone :one
UPDATE print_jobs SET marked_done_at = now(), updated_at = now()
WHERE id = $1 AND parent_id = $2 AND marked_done_at IS NULL
RETURNING id, child_id, template_code, payload, marked_done_at
`

type MarkPrintJobDoneParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

type MarkPrintJobDoneRow struct {
	ID           uuid.UUID          `json:"id"`
	ChildID      uuid.UUID          `json:"child_id"`
	TemplateCode string             `json:"template_code"`
	Payload      []byte             `json:"payload"`
	MarkedDoneAt pgtype.Timestamptz `json:"marked_done_at"`
}

// 纸质补录标记：只在还没标过的时候写，返回标记时间；已标过返回 0 行，service 据此判幂等。
func (q *Queries) MarkPrintJobDone(ctx context.Context, arg MarkPrintJobDoneParams) (MarkPrintJobDoneRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobDone, arg.ID, arg.ParentID)
	var i MarkPrintJobDoneRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Payload,
		&i.MarkedDoneAt,
	)
	return i, err
}

const markPrintJobFailed = `-- name: MarkPrintJobFailed :exec
UPDATE print_jobs SET
    status        = 'failed',
    error_message = $1,
    updated_at    = now()
WHERE id = $2
`

type MarkPrintJobFailedParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) MarkPrintJobFailed(ctx context.Context, arg MarkPrintJobFailedParams) error {
	_, err := q.db.Exec(ctx, markPrintJobFailed, arg.ErrorMessage, arg.ID)
	return err
}

const markPrintJobQueued = `-- name: MarkPrintJobQueued :one

UPDATE print_jobs SET
    status        = CASE WHEN status IN ('created', 'failed') THEN 'queued' ELSE status END,
    error_message = CASE WHEN status IN ('created', 'failed') THEN '' ELSE error_message END,
    pdf_path      = CASE WHEN status = 'failed' THEN NULL ELSE pdf_path END,
    updated_at    = now()
WHERE id = $1 AND parent_id = $2
RETURNING id, status, pdf_path, page_count, error_message
`

type MarkPrintJobQueuedParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

type MarkPrintJobQueuedRow struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	PdfPath      pgtype.Text `json:"pdf_path"`
	PageCount    int32       `json:"page_count"`
	ErrorMessage string      `json:"error_message"`
}

// ---------------------------------------------------------------- 状态机
// 排队渲染：created / failed 才允许重新排队；ready 重复调用不改变状态（幂等）。
func (q *Queries) MarkPrintJobQueued(ctx context.Context, arg MarkPrintJobQueuedParams) (MarkPrintJobQueuedRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobQueued, arg.ID, arg.ParentID)
	var i MarkPrintJobQueuedRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PdfPath,
		&i.PageCount,
		&i.ErrorMessage,
	)
	return i, err
}

const markPrintJobReady = `-- name: MarkPrintJobReady :one
UPDATE print_jobs SET
    status     = 'ready',
    pdf_path   = $1,
    page_count = $2,
    error_message = '',
    updated_at = now()
WHERE id = $3
RETURNING id, status, pdf_path, page_count
`

type MarkPrintJobReadyParams struct {
	PdfPath   pgtype.Text `json:"pdf_path"`
	PageCount int32       `json:"page_count"`
	ID        uuid.UUID   `json:"id"`
}

type MarkPrintJobReadyRow struct {
	ID        uuid.UUID   `json:"id"`
	Status    string      `json:"status"`
	PdfPath   pgtype.Text `json:"pdf_path"`
	PageCount int32       `json:"page_count"`
}

func (q *Queries) MarkPrintJobReady(ctx context.Context, arg MarkPrintJobReadyParams) (MarkPrintJobReadyRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobReady, arg.PdfPath, arg.PageCount, arg.ID)
	var i MarkPrintJobReadyRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PdfPath,
		&i.PageCount,
	)
	return i, err
}

const printChildBasic = `-- name: PrintChildBasic :one

SELECT id, nickname, stage_code
FROM children
WHERE id = $1 AND parent_id = $2 AND active
`

type PrintChildBasicParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

type PrintChildBasicRow struct {
	ID        uuid.UUID   `json:"id"`
	Nickname  string      `json:"nickname"`
	StageCode pgtype.Text `json:"stage_code"`
}

// ---------------------------------------------------------------- 取数（渲染题面用）
// 归属校验：parent_id 一起过滤，越权当作不存在（与 children 模块的 404 约定一致）。
func (q *Queries) PrintChildBasic(ctx context.Context, arg PrintChildBasicParams) (PrintChildBasicRow, error) {
	row := q.db.QueryRow(ctx, printChildBasic, arg.ID, arg.ParentID)
	var i PrintChildBasicRow
	err := row.Scan(&i.ID, &i.Nickname, &i.StageCode)
	return i, err
}

const printGetStory = `-- name: PrintGetStory :one
SELECT id, title, lang, level_code, body_md, questions, discussion, char_count
FROM stories
WHERE id = $1 AND status = 'published' AND suitable
`

type PrintGetStoryRow struct {
	ID         uuid.UUID   `json:"id"`
	Title      string      `json:"title"`
	Lang       string      `json:"lang"`
	LevelCode  pgtype.Text `json:"level_code"`
	BodyMd     string      `json:"body_md"`
	Questions  []byte      `json:"questions"`
	Discussion []byte      `json:"discussion"`
	CharCount  int32       `json:"char_count"`
}

// 故事小册子：指定故事，或按级别挑一篇最短的（篇幅短的更适合一次朗读完）。
// 只取已发布且通过适宜性筛查的，与孩子端的可见口径保持一致。
func (q *Queries) PrintGetStory(ctx context.Context, id uuid.UUID) (PrintGetStoryRow, error) {
	row := q.db.QueryRow(ctx, printGetStory, id)
	var i PrintGetStoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lang,
		&i.LevelCode,
		&i.BodyMd,
		&i.Questions,
		&i.Discussion,
		&i.CharCount,
	)
	return i, err
}

const printKPsByStage = `-- name: PrintKPsByStage :many
SELECT id, subject_code, kind, name, difficulty
FROM knowledge_points
WHERE subject_code = $1
  AND ($2::text = '' OR stage_code = $2::text)
  AND status = 'published'
ORDER BY difficulty, code
LIMIT $3
`

type PrintKPsByStageParams struct {
	SubjectCode string `json:"subject_code"`
	StageCode   string `json:"stage_code"`
	Lim         int32  `json:"lim"`
}

type PrintKPsByStageRow struct {
	ID          uuid.UUID `json:"id"`
	SubjectCode string    `json:"subject_code"`
	Kind        string    `json:"kind"`
	Name        string    `json:"name"`
	Difficulty  int16     `json:"difficulty"`
}

// 范围一：按阶段取（家长手动挑「S2 的字」这类）
func (q *Queries) PrintKPsByStage(ctx context.Context, arg PrintKPsByStageParams) ([]PrintKPsByStageRow, error) {
	rows, err := q.db.Query(ctx, printKPsByStage, arg.SubjectCode, arg.StageCode, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrintKPsByStageRow{}
	for rows.Next() {
		var i PrintKPsByStageRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectCode,
			&i.Kind,
			&i.Name,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printKPsMastered = `-- name: PrintKPsMastered :many
SELECT kp_id
FROM mastery_records
WHERE child_id = $1 AND level >= $2
ORDER BY COALESCE(mastered_at, first_learned_at) DESC NULLS LAST, kp_id
LIMIT $3
`

type PrintKPsMasteredParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	MinLevel int16     `json:"min_level"`
	Lim      int32     `json:"lim"`
}

// 范围四：已掌握（做闪卡复习用）
func (q *Queries) PrintKPsMastered(ctx context.Context, arg PrintKPsMasteredParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, printKPsMastered, arg.ChildID, arg.MinLevel, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var kp_id uuid.UUID
		if err := rows.Scan(&kp_id); err != nil {
			return nil, err
		}
		items = append(items, kp_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printKPsRecent = `-- name: PrintKPsRecent :many
SELECT DISTINCT kp_id
FROM mastery_records
WHERE child_id = $1
  AND COALESCE(mastered_at, first_learned_at) IS NOT NULL
  AND COALESCE(mastered_at, first_learned_at) >= $2
ORDER BY kp_id
LIMIT $3
`

type PrintKPsRecentParams struct {
	ChildID uuid.UUID          `json:"child_id"`
	Since   pgtype.Timestamptz `json:"since"`
	Lim     int32              `json:"lim"`
}

// 范围二：近期新学（默认「本周」= 近 7 天）—— 时间点由 Go 侧算好传进来，
// 不在 SQL 里做 now() - interval 的推算，免得 sqlc 对 interval 参数推断出意外类型。
func (q *Queries) PrintKPsRecent(ctx context.Context, arg PrintKPsRecentParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, printKPsRecent, arg.ChildID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var kp_id uuid.UUID
		if err := rows.Scan(&kp_id); err != nil {
			return nil, err
		}
		items = append(items, kp_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printKPsWrongBook = `-- name: PrintKPsWrongBook :many
SELECT kp_id
FROM wrong_book_entries
WHERE child_id = $1 AND cleared_at IS NULL
ORDER BY added_at DESC, kp_id
LIMIT $2
`

type PrintKPsWrongBookParams struct {
	ChildID uuid.UUID `json:"child_id"`
	Lim     int32     `json:"lim"`
}

// 范围三：错题本（未移出的）
func (q *Queries) PrintKPsWrongBook(ctx context.Context, arg PrintKPsWrongBookParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, printKPsWrongBook, arg.ChildID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var kp_id uuid.UUID
		if err := rows.Scan(&kp_id); err != nil {
			return nil, err
		}
		items = append(items, kp_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printMathKPByTemplate = `-- name: PrintMathKPByTemplate :one
SELECT id
FROM knowledge_points
WHERE kind = 'math_skill' AND metadata->>'template_code' = $1::text
LIMIT 1
`

// 数学题的补录挂点：一道口算题卡属于哪个知识点。数学题的 kp 是「题型档」不是单题，
// 所以整张卷子补录只推进这一个技能点（§4.6 步骤 6）。用 metadata 里的 template_code
// 关联，与 M3 播种时的写入口径一致。
func (q *Queries) PrintMathKPByTemplate(ctx context.Context, templateCode string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, printMathKPByTemplate, templateCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const printPickStory = `-- name: PrintPickStory :one
SELECT id, title, lang, level_code, body_md, questions, discussion, char_count
FROM stories
WHERE status = 'published' AND suitable
  AND ($1::text = '' OR level_code = $1::text)
ORDER BY char_count, id
LIMIT 1
`

type PrintPickStoryRow struct {
	ID         uuid.UUID   `json:"id"`
	Title      string      `json:"title"`
	Lang       string      `json:"lang"`
	LevelCode  pgtype.Text `json:"level_code"`
	BodyMd     string      `json:"body_md"`
	Questions  []byte      `json:"questions"`
	Discussion []byte      `json:"discussion"`
	CharCount  int32       `json:"char_count"`
}

func (q *Queries) PrintPickStory(ctx context.Context, stageCode string) (PrintPickStoryRow, error) {
	row := q.db.QueryRow(ctx, printPickStory, stageCode)
	var i PrintPickStoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lang,
		&i.LevelCode,
		&i.BodyMd,
		&i.Questions,
		&i.Discussion,
		&i.CharCount,
	)
	return i, err
}

const requeueStaleRendering = `-- name: RequeueStaleRendering :exec
UPDATE print_jobs SET status = 'queued', updated_at = now()
WHERE status = 'rendering' AND updated_at < now() - make_interval(secs => $1::double precision)
`

// 渲染中的任务超过 staleSec 视为进程崩溃遗留，退回 queued 重试（幂等：worker 启动时跑一次）。
func (q *Queries) RequeueStaleRendering(ctx context.Context, staleSec float64) error {
	_, err := q.db.Exec(ctx, requeueStaleRendering, staleSec)
	return err
}
