// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: print.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPrintJobs = `-- name: ClaimPrintJobs :many
WITH claimed AS (
    SELECT id FROM print_jobs
    WHERE status = 'queued'
    ORDER BY created_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE print_jobs p SET status = 'rendering', updated_at = now()
FROM claimed c
WHERE p.id = c.id
RETURNING p.id, p.child_id, p.template_code, p.payload, p.page_count
`

type ClaimPrintJobsRow struct {
	ID           uuid.UUID `json:"id"`
	ChildID      uuid.UUID `json:"child_id"`
	TemplateCode string    `json:"template_code"`
	Payload      []byte    `json:"payload"`
	PageCount    int32     `json:"page_count"`
}

// worker 拉取待渲染任务（多实例安全）。
func (q *Queries) ClaimPrintJobs(ctx context.Context, lim int32) ([]ClaimPrintJobsRow, error) {
	rows, err := q.db.Query(ctx, claimPrintJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPrintJobsRow{}
	for rows.Next() {
		var i ClaimPrintJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TemplateCode,
			&i.Payload,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPrintJobs = `-- name: CountPrintJobs :one
SELECT count(*)::bigint AS total
FROM print_jobs
WHERE parent_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid
       OR child_id = $2::uuid)
`

type CountPrintJobsParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ChildID  uuid.UUID `json:"child_id"`
}

func (q *Queries) CountPrintJobs(ctx context.Context, arg CountPrintJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrintJobs, arg.ParentID, arg.ChildID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPrintJob = `-- name: CreatePrintJob :one


INSERT INTO print_jobs (parent_id, child_id, template_code, params, payload, page_count)
VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    $5::jsonb,
    $6
)
RETURNING id, parent_id, child_id, template_code, params, payload, page_count,
          pdf_path, status, error_message, marked_done_at, created_at, updated_at
`

type CreatePrintJobParams struct {
	ParentID     uuid.UUID `json:"parent_id"`
	ChildID      uuid.UUID `json:"child_id"`
	TemplateCode string    `json:"template_code"`
	Params       []byte    `json:"params"`
	Payload      []byte    `json:"payload"`
	PageCount    int32     `json:"page_count"`
}

// 打印中心的查询（§4.6）。
//
// 约定：
//  1. payload 是自洽的数据快照：worker 渲染 PDF 时只依赖它 + template_code，
//     不再回查 content/mastery —— 否则模板改版或内容下线会让历史任务渲染不出原样。
//  2. 「无过滤」用哨兵值表示（child_id = 全零 uuid），与 content.sql 用 ” 表示无过滤一致，
//     避免 sqlc 在可空参数上的类型推断歧义。
//  3. worker 取任务用 FOR UPDATE SKIP LOCKED，多实例并行拉取不会重复渲染同一个 job。
//
// ---------------------------------------------------------------- 建与读
func (q *Queries) CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, createPrintJob,
		arg.ParentID,
		arg.ChildID,
		arg.TemplateCode,
		arg.Params,
		arg.Payload,
		arg.PageCount,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Params,
		&i.Payload,
		&i.PageCount,
		&i.PdfPath,
		&i.Status,
		&i.ErrorMessage,
		&i.MarkedDoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrintJob = `-- name: GetPrintJob :one
SELECT id, parent_id, child_id, template_code, params, payload, page_count,
       pdf_path, status, error_message, marked_done_at, created_at, updated_at
FROM print_jobs
WHERE id = $1 AND parent_id = $2
`

type GetPrintJobParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

func (q *Queries) GetPrintJob(ctx context.Context, arg GetPrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, getPrintJob, arg.ID, arg.ParentID)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Params,
		&i.Payload,
		&i.PageCount,
		&i.PdfPath,
		&i.Status,
		&i.ErrorMessage,
		&i.MarkedDoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrintSession = `-- name: InsertPrintSession :one
INSERT INTO learning_sessions (
    child_id, device_type, started_at, ended_at, question_count, answered_count,
    correct_count, star_count, completed_by, parent_note, status, print_job_id
)
VALUES (
    $1, 'print', now(), now(),
    $2, $3, $4,
    0, 'parent', $5, 'finished', $6
)
RETURNING id
`

type InsertPrintSessionParams struct {
	ChildID       uuid.UUID   `json:"child_id"`
	QuestionCount int32       `json:"question_count"`
	AnsweredCount int32       `json:"answered_count"`
	CorrectCount  int32       `json:"correct_count"`
	ParentNote    pgtype.Text `json:"parent_note"`
	PrintJobID    pgtype.UUID `json:"print_job_id"`
}

// 补录产生的学习会话：completed_by='parent'，并回指到 print_job，报表可区分来源（§4.11）。
func (q *Queries) InsertPrintSession(ctx context.Context, arg InsertPrintSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPrintSession,
		arg.ChildID,
		arg.QuestionCount,
		arg.AnsweredCount,
		arg.CorrectCount,
		arg.ParentNote,
		arg.PrintJobID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPrintJobs = `-- name: ListPrintJobs :many
SELECT id, parent_id, child_id, template_code, params, payload, page_count,
       pdf_path, status, error_message, marked_done_at, created_at, updated_at
FROM print_jobs
WHERE parent_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid
       OR child_id = $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListPrintJobsParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ChildID  uuid.UUID `json:"child_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListPrintJobs(ctx context.Context, arg ListPrintJobsParams) ([]PrintJob, error) {
	rows, err := q.db.Query(ctx, listPrintJobs,
		arg.ParentID,
		arg.ChildID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ChildID,
			&i.TemplateCode,
			&i.Params,
			&i.Payload,
			&i.PageCount,
			&i.PdfPath,
			&i.Status,
			&i.ErrorMessage,
			&i.MarkedDoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPrintJobDone = `-- name: MarkPrintJobDone :one
UPDATE print_jobs SET marked_done_at = now(), updated_at = now()
WHERE id = $1 AND parent_id = $2 AND marked_done_at IS NULL
RETURNING id, child_id, template_code, payload, marked_done_at
`

type MarkPrintJobDoneParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

type MarkPrintJobDoneRow struct {
	ID           uuid.UUID          `json:"id"`
	ChildID      uuid.UUID          `json:"child_id"`
	TemplateCode string             `json:"template_code"`
	Payload      []byte             `json:"payload"`
	MarkedDoneAt pgtype.Timestamptz `json:"marked_done_at"`
}

// 纸质补录标记：只在还没标过的时候写，返回标记时间；已标过返回 0 行，service 据此判幂等。
func (q *Queries) MarkPrintJobDone(ctx context.Context, arg MarkPrintJobDoneParams) (MarkPrintJobDoneRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobDone, arg.ID, arg.ParentID)
	var i MarkPrintJobDoneRow
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TemplateCode,
		&i.Payload,
		&i.MarkedDoneAt,
	)
	return i, err
}

const markPrintJobFailed = `-- name: MarkPrintJobFailed :exec
UPDATE print_jobs SET
    status        = 'failed',
    error_message = $1,
    updated_at    = now()
WHERE id = $2
`

type MarkPrintJobFailedParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) MarkPrintJobFailed(ctx context.Context, arg MarkPrintJobFailedParams) error {
	_, err := q.db.Exec(ctx, markPrintJobFailed, arg.ErrorMessage, arg.ID)
	return err
}

const markPrintJobQueued = `-- name: MarkPrintJobQueued :one

UPDATE print_jobs SET
    status        = CASE WHEN status IN ('created', 'failed') THEN 'queued' ELSE status END,
    error_message = CASE WHEN status IN ('created', 'failed') THEN '' ELSE error_message END,
    pdf_path      = CASE WHEN status = 'failed' THEN NULL ELSE pdf_path END,
    updated_at    = now()
WHERE id = $1 AND parent_id = $2
RETURNING id, status, pdf_path, page_count, error_message
`

type MarkPrintJobQueuedParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

type MarkPrintJobQueuedRow struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	PdfPath      pgtype.Text `json:"pdf_path"`
	PageCount    int32       `json:"page_count"`
	ErrorMessage string      `json:"error_message"`
}

// ---------------------------------------------------------------- 状态机
// 排队渲染：created / failed 才允许重新排队；ready 重复调用不改变状态（幂等）。
func (q *Queries) MarkPrintJobQueued(ctx context.Context, arg MarkPrintJobQueuedParams) (MarkPrintJobQueuedRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobQueued, arg.ID, arg.ParentID)
	var i MarkPrintJobQueuedRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PdfPath,
		&i.PageCount,
		&i.ErrorMessage,
	)
	return i, err
}

const markPrintJobReady = `-- name: MarkPrintJobReady :one
UPDATE print_jobs SET
    status     = 'ready',
    pdf_path   = $1,
    page_count = $2,
    error_message = '',
    updated_at = now()
WHERE id = $3
RETURNING id, status, pdf_path, page_count
`

type MarkPrintJobReadyParams struct {
	PdfPath   pgtype.Text `json:"pdf_path"`
	PageCount int32       `json:"page_count"`
	ID        uuid.UUID   `json:"id"`
}

type MarkPrintJobReadyRow struct {
	ID        uuid.UUID   `json:"id"`
	Status    string      `json:"status"`
	PdfPath   pgtype.Text `json:"pdf_path"`
	PageCount int32       `json:"page_count"`
}

func (q *Queries) MarkPrintJobReady(ctx context.Context, arg MarkPrintJobReadyParams) (MarkPrintJobReadyRow, error) {
	row := q.db.QueryRow(ctx, markPrintJobReady, arg.PdfPath, arg.PageCount, arg.ID)
	var i MarkPrintJobReadyRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PdfPath,
		&i.PageCount,
	)
	return i, err
}

const requeueStaleRendering = `-- name: RequeueStaleRendering :exec
UPDATE print_jobs SET status = 'queued', updated_at = now()
WHERE status = 'rendering' AND updated_at < now() - make_interval(secs => $1::double precision)
`

// 渲染中的任务超过 staleSec 视为进程崩溃遗留，退回 queued 重试（幂等：worker 启动时跑一次）。
func (q *Queries) RequeueStaleRendering(ctx context.Context, staleSec float64) error {
	_, err := q.db.Exec(ctx, requeueStaleRendering, staleSec)
	return err
}
