// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountEnWords(ctx context.Context, arg CountEnWordsParams) (int64, error)
	CountHanzi(ctx context.Context, arg CountHanziParams) (int64, error)
	CountPlanForChild(ctx context.Context, childID uuid.UUID) (int64, error)
	CountReviewQueue(ctx context.Context, arg CountReviewQueueParams) (int64, error)
	CountStories(ctx context.Context, arg CountStoriesParams) (int64, error)
	DecideReview(ctx context.Context, arg DecideReviewParams) (DecideReviewRow, error)
	GetHanziByChar(ctx context.Context, char string) (Hanzi, error)
	GetHanziByID(ctx context.Context, id uuid.UUID) (Hanzi, error)
	GetReviewByID(ctx context.Context, id uuid.UUID) (ContentReview, error)
	GetStoryByID(ctx context.Context, id uuid.UUID) (GetStoryByIDRow, error)
	GetStoryPair(ctx context.Context, zhStoryID uuid.UUID) (GetStoryPairRow, error)
	InsertPlanRow(ctx context.Context, arg InsertPlanRowParams) error
	ListChildrenForPlan(ctx context.Context) ([]ListChildrenForPlanRow, error)
	ListEnWords(ctx context.Context, arg ListEnWordsParams) ([]ListEnWordsRow, error)
	ListHanzi(ctx context.Context, arg ListHanziParams) ([]ListHanziRow, error)
	ListHanziWords(ctx context.Context, hanziIds []uuid.UUID) ([]ListHanziWordsRow, error)
	ListPlannedKPs(ctx context.Context, arg ListPlannedKPsParams) ([]ListPlannedKPsRow, error)
	ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error)
	// 内容模块的读查询（sqlc 生成到 internal/feature/content/dbgen）。
	//
	// 约定：
	//  1. 列表查询一律「过滤器为空字符串即不过滤」，避免为每种组合写一条 SQL；
	//  2. pinyin / stroke_paths / images 等 jsonb 列在 repository 层再解析成领域结构；
	//  3. 批量导入走 internal/feature/content/bulk.go 的多行 upsert（sqlc 不做批量写）。
	ListStages(ctx context.Context, subjectCode string) ([]ListStagesRow, error)
	ListStories(ctx context.Context, arg ListStoriesParams) ([]ListStoriesRow, error)
	PublishStory(ctx context.Context, id uuid.UUID) (int64, error)
	RejectStory(ctx context.Context, id uuid.UUID) (int64, error)
	UpsertStage(ctx context.Context, arg UpsertStageParams) error
}

var _ Querier = (*Queries)(nil)
