// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const badgeMasteryStats = `-- name: BadgeMasteryStats :one
SELECT
    count(*)::bigint                                            AS mastered_total,
    count(*) FILTER (WHERE k.subject_code = 'chinese')::bigint  AS mastered_chinese,
    count(*) FILTER (WHERE k.subject_code = 'math')::bigint     AS mastered_math,
    count(*) FILTER (WHERE k.subject_code = 'english')::bigint  AS mastered_english
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1 AND m.level >= 3
`

type BadgeMasteryStatsRow struct {
	MasteredTotal   int64 `json:"mastered_total"`
	MasteredChinese int64 `json:"mastered_chinese"`
	MasteredMath    int64 `json:"mastered_math"`
	MasteredEnglish int64 `json:"mastered_english"`
}

func (q *Queries) BadgeMasteryStats(ctx context.Context, childID uuid.UUID) (BadgeMasteryStatsRow, error) {
	row := q.db.QueryRow(ctx, badgeMasteryStats, childID)
	var i BadgeMasteryStatsRow
	err := row.Scan(
		&i.MasteredTotal,
		&i.MasteredChinese,
		&i.MasteredMath,
		&i.MasteredEnglish,
	)
	return i, err
}

const badgeSessionStats = `-- name: BadgeSessionStats :one
SELECT
    count(*)::bigint                                            AS session_count,
    count(*) FILTER (WHERE answered_count > 0 AND correct_count = answered_count)::bigint AS perfect_sessions,
    COALESCE(sum(star_count), 0)::bigint                        AS star_total
FROM learning_sessions
WHERE child_id = $1 AND status = 'finished'
`

type BadgeSessionStatsRow struct {
	SessionCount    int64 `json:"session_count"`
	PerfectSessions int64 `json:"perfect_sessions"`
	StarTotal       int64 `json:"star_total"`
}

// 成就评测素材（一次取全，评测器在 Go 侧判定）
func (q *Queries) BadgeSessionStats(ctx context.Context, childID uuid.UUID) (BadgeSessionStatsRow, error) {
	row := q.db.QueryRow(ctx, badgeSessionStats, childID)
	var i BadgeSessionStatsRow
	err := row.Scan(&i.SessionCount, &i.PerfectSessions, &i.StarTotal)
	return i, err
}

const insertChildBadge = `-- name: InsertChildBadge :one
INSERT INTO child_badges (child_id, badge_id, progress)
VALUES ($1, $2, $3)
ON CONFLICT (child_id, badge_id) DO NOTHING
RETURNING id
`

type InsertChildBadgeParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	BadgeID  uuid.UUID `json:"badge_id"`
	Progress []byte    `json:"progress"`
}

// 授予（幂等）：已授予过就不动，返回是否本次新发
func (q *Queries) InsertChildBadge(ctx context.Context, arg InsertChildBadgeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertChildBadge, arg.ChildID, arg.BadgeID, arg.Progress)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBadges = `-- name: ListBadges :many

SELECT id, code, name, category, description, icon, rule, sort_order
FROM badges
WHERE active
ORDER BY sort_order, code
`

type ListBadgesRow struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Rule        []byte    `json:"rule"`
	SortOrder   int32     `json:"sort_order"`
}

// ---------------------------------------------------------------- 成就
func (q *Queries) ListBadges(ctx context.Context) ([]ListBadgesRow, error) {
	rows, err := q.db.Query(ctx, listBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBadgesRow{}
	for rows.Next() {
		var i ListBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Icon,
			&i.Rule,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildBadges = `-- name: ListChildBadges :many
SELECT cb.id, cb.badge_id, cb.earned_at, cb.progress,
       b.code, b.name, b.category, b.description, b.icon, b.sort_order
FROM child_badges cb
JOIN badges b ON b.id = cb.badge_id
WHERE cb.child_id = $1
ORDER BY cb.earned_at DESC
`

type ListChildBadgesRow struct {
	ID          uuid.UUID          `json:"id"`
	BadgeID     uuid.UUID          `json:"badge_id"`
	EarnedAt    pgtype.Timestamptz `json:"earned_at"`
	Progress    []byte             `json:"progress"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
	SortOrder   int32              `json:"sort_order"`
}

func (q *Queries) ListChildBadges(ctx context.Context, childID uuid.UUID) ([]ListChildBadgesRow, error) {
	rows, err := q.db.Query(ctx, listChildBadges, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildBadgesRow{}
	for rows.Next() {
		var i ListChildBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.BadgeID,
			&i.EarnedAt,
			&i.Progress,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Icon,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildIDs = `-- name: ListChildIDs :many

SELECT id, parent_id FROM children ORDER BY created_at
`

type ListChildIDsRow struct {
	ID       uuid.UUID `json:"id"`
	ParentID uuid.UUID `json:"parent_id"`
}

// ---------------------------------------------------------------- 日汇总 worker
// 全量孩子（含活跃与已归档，归档孩子不铺新线但仍可重算历史）
func (q *Queries) ListChildIDs(ctx context.Context) ([]ListChildIDsRow, error) {
	rows, err := q.db.Query(ctx, listChildIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildIDsRow{}
	for rows.Next() {
		var i ListChildIDsRow
		if err := rows.Scan(&i.ID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassedDaysDesc = `-- name: ListPassedDaysDesc :many
SELECT stat_date
FROM daily_stats
WHERE child_id = $1
  AND subject_code = ''
  AND passed
ORDER BY stat_date DESC
LIMIT $2
`

type ListPassedDaysDescParams struct {
	ChildID uuid.UUID `json:"child_id"`
	Lim     int32     `json:"lim"`
}

// 连续达标天数（从今天往回数，遇到未达标即停）
func (q *Queries) ListPassedDaysDesc(ctx context.Context, arg ListPassedDaysDescParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listPassedDaysDesc, arg.ChildID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var stat_date pgtype.Date
		if err := rows.Scan(&stat_date); err != nil {
			return nil, err
		}
		items = append(items, stat_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parentSettingsFull = `-- name: ParentSettingsFull :one

SELECT parent_id, daily_limit_min, session_limit_min, rest_interval_min,
       require_parent_confirm, pace_mode, compare_children
FROM parent_settings
WHERE parent_id = $1
`

type ParentSettingsFullRow struct {
	ParentID             uuid.UUID `json:"parent_id"`
	DailyLimitMin        int32     `json:"daily_limit_min"`
	SessionLimitMin      int32     `json:"session_limit_min"`
	RestIntervalMin      int32     `json:"rest_interval_min"`
	RequireParentConfirm bool      `json:"require_parent_confirm"`
	PaceMode             string    `json:"pace_mode"`
	CompareChildren      bool      `json:"compare_children"`
}

// ---------------------------------------------------------------- 家长设置
// 家长设置的完整视图（含 compare_children）；parent 模块专用，
// 不动 learning.sql 里 practice 已经在用的 GetParentSettings，避免连带影响。
func (q *Queries) ParentSettingsFull(ctx context.Context, parentID uuid.UUID) (ParentSettingsFullRow, error) {
	row := q.db.QueryRow(ctx, parentSettingsFull, parentID)
	var i ParentSettingsFullRow
	err := row.Scan(
		&i.ParentID,
		&i.DailyLimitMin,
		&i.SessionLimitMin,
		&i.RestIntervalMin,
		&i.RequireParentConfirm,
		&i.PaceMode,
		&i.CompareChildren,
	)
	return i, err
}

const reportChildrenInfo = `-- name: ReportChildrenInfo :many
SELECT id, nickname, avatar_id, stage_code
FROM children
WHERE parent_id = $1
  AND id = ANY($2::uuid[])
ORDER BY created_at
`

type ReportChildrenInfoParams struct {
	ParentID uuid.UUID   `json:"parent_id"`
	ChildIds []uuid.UUID `json:"child_ids"`
}

type ReportChildrenInfoRow struct {
	ID        uuid.UUID   `json:"id"`
	Nickname  string      `json:"nickname"`
	AvatarID  string      `json:"avatar_id"`
	StageCode pgtype.Text `json:"stage_code"`
}

// 对比用的孩子基本信息；带 parent_id 过滤顺带完成归属校验（只会拿到自己的孩子）
func (q *Queries) ReportChildrenInfo(ctx context.Context, arg ReportChildrenInfoParams) ([]ReportChildrenInfoRow, error) {
	rows, err := q.db.Query(ctx, reportChildrenInfo, arg.ParentID, arg.ChildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportChildrenInfoRow{}
	for rows.Next() {
		var i ReportChildrenInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.AvatarID,
			&i.StageCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailyAnswers = `-- name: ReportDailyAnswers :many
SELECT
    (a.created_at AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    count(*)::bigint                                   AS attempts,
    count(*) FILTER (WHERE a.is_correct)::bigint        AS correct_count
FROM answer_logs a
WHERE a.child_id = $1
  AND ($2::text = '' OR a.subject_code = $2::text)
GROUP BY 1
ORDER BY 1
`

type ReportDailyAnswersParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
}

type ReportDailyAnswersRow struct {
	StatDate     pgtype.Date `json:"stat_date"`
	Attempts     int64       `json:"attempts"`
	CorrectCount int64       `json:"correct_count"`
}

// 逐日作答数（对比里的正确率/重复次数按天聚合）
func (q *Queries) ReportDailyAnswers(ctx context.Context, arg ReportDailyAnswersParams) ([]ReportDailyAnswersRow, error) {
	rows, err := q.db.Query(ctx, reportDailyAnswers, arg.ChildID, arg.SubjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDailyAnswersRow{}
	for rows.Next() {
		var i ReportDailyAnswersRow
		if err := rows.Scan(&i.StatDate, &i.Attempts, &i.CorrectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailyDuration = `-- name: ReportDailyDuration :many
SELECT
    (COALESCE(s.ended_at, s.started_at) AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    COALESCE(sum(s.duration_sec), 0)::bigint AS duration_sec
FROM learning_sessions s
WHERE s.child_id = $1
  AND s.status = 'finished'
GROUP BY 1
ORDER BY 1
`

type ReportDailyDurationRow struct {
	StatDate    pgtype.Date `json:"stat_date"`
	DurationSec int64       `json:"duration_sec"`
}

// 逐日学习时长（对比里的「每日时长/学习天数」）
func (q *Queries) ReportDailyDuration(ctx context.Context, childID uuid.UUID) ([]ReportDailyDurationRow, error) {
	rows, err := q.db.Query(ctx, reportDailyDuration, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDailyDurationRow{}
	for rows.Next() {
		var i ReportDailyDurationRow
		if err := rows.Scan(&i.StatDate, &i.DurationSec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailyMastered = `-- name: ReportDailyMastered :many

SELECT
    (m.mastered_at AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    count(*)::bigint                                    AS mastered_count
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.mastered_at IS NOT NULL
  AND ($2::text = '' OR k.subject_code = $2::text)
GROUP BY 1
ORDER BY 1
`

type ReportDailyMasteredParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
}

type ReportDailyMasteredRow struct {
	StatDate      pgtype.Date `json:"stat_date"`
	MasteredCount int64       `json:"mastered_count"`
}

// ---------------------------------------------------------------- 多孩对比（§4.10）
// 逐日新掌握数（用于按「学习日序号」或自然日累加）
func (q *Queries) ReportDailyMastered(ctx context.Context, arg ReportDailyMasteredParams) ([]ReportDailyMasteredRow, error) {
	rows, err := q.db.Query(ctx, reportDailyMastered, arg.ChildID, arg.SubjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDailyMasteredRow{}
	for rows.Next() {
		var i ReportDailyMasteredRow
		if err := rows.Scan(&i.StatDate, &i.MasteredCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailySeries = `-- name: ReportDailySeries :many

SELECT stat_date, subject_code, duration_sec, question_count, correct_count,
       new_mastered, star_count, planned_new, actual_new, repeat_count,
       cum_planned, cum_actual, deviation_days, passed, parent_confirmed
FROM daily_stats
WHERE child_id = $1
  AND stat_date >= $2
  AND stat_date <= $3
  AND ($4::text = '' OR subject_code = $4::text)
ORDER BY stat_date, subject_code
`

type ReportDailySeriesParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	SubjectCode string      `json:"subject_code"`
}

type ReportDailySeriesRow struct {
	StatDate        pgtype.Date `json:"stat_date"`
	SubjectCode     string      `json:"subject_code"`
	DurationSec     int32       `json:"duration_sec"`
	QuestionCount   int32       `json:"question_count"`
	CorrectCount    int32       `json:"correct_count"`
	NewMastered     int32       `json:"new_mastered"`
	StarCount       int32       `json:"star_count"`
	PlannedNew      int32       `json:"planned_new"`
	ActualNew       int32       `json:"actual_new"`
	RepeatCount     int32       `json:"repeat_count"`
	CumPlanned      int32       `json:"cum_planned"`
	CumActual       int32       `json:"cum_actual"`
	DeviationDays   float64     `json:"deviation_days"`
	Passed          bool        `json:"passed"`
	ParentConfirmed bool        `json:"parent_confirmed"`
}

// ---------------------------------------------------------------- 趋势
// 逐日趋势：返回 ” 合计行与分学科行，service 按需归拢。
func (q *Queries) ReportDailySeries(ctx context.Context, arg ReportDailySeriesParams) ([]ReportDailySeriesRow, error) {
	rows, err := q.db.Query(ctx, reportDailySeries,
		arg.ChildID,
		arg.FromDate,
		arg.ToDate,
		arg.SubjectCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDailySeriesRow{}
	for rows.Next() {
		var i ReportDailySeriesRow
		if err := rows.Scan(
			&i.StatDate,
			&i.SubjectCode,
			&i.DurationSec,
			&i.QuestionCount,
			&i.CorrectCount,
			&i.NewMastered,
			&i.StarCount,
			&i.PlannedNew,
			&i.ActualNew,
			&i.RepeatCount,
			&i.CumPlanned,
			&i.CumActual,
			&i.DeviationDays,
			&i.Passed,
			&i.ParentConfirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDueCount = `-- name: ReportDueCount :one
SELECT count(*)::bigint
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.level > 0
  AND m.next_review_at <= $2
  AND ($3::text = '' OR k.subject_code = $3::text)
`

type ReportDueCountParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	NowTs       pgtype.Timestamptz `json:"now_ts"`
	SubjectCode string             `json:"subject_code"`
}

// 待复习 / 积压（复习队列长度，用于「设为复习日」建议与总览）
func (q *Queries) ReportDueCount(ctx context.Context, arg ReportDueCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, reportDueCount, arg.ChildID, arg.NowTs, arg.SubjectCode)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reportEfficiencyTotal = `-- name: ReportEfficiencyTotal :one
SELECT
    count(*)::bigint                               AS mastered_count,
    COALESCE(sum(m.attempts_to_master), 0)::bigint AS attempts_sum,
    COALESCE(avg(m.attempts_to_master), 0)::float8 AS attempts_per_mastery
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.level >= 3
  AND ($2::text = '' OR k.subject_code = $2::text)
`

type ReportEfficiencyTotalParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
}

type ReportEfficiencyTotalRow struct {
	MasteredCount      int64   `json:"mastered_count"`
	AttemptsSum        int64   `json:"attempts_sum"`
	AttemptsPerMastery float64 `json:"attempts_per_mastery"`
}

// 掌握一个知识点平均要作答几次（§4.9 学习效率口径）
func (q *Queries) ReportEfficiencyTotal(ctx context.Context, arg ReportEfficiencyTotalParams) (ReportEfficiencyTotalRow, error) {
	row := q.db.QueryRow(ctx, reportEfficiencyTotal, arg.ChildID, arg.SubjectCode)
	var i ReportEfficiencyTotalRow
	err := row.Scan(&i.MasteredCount, &i.AttemptsSum, &i.AttemptsPerMastery)
	return i, err
}

const reportFirstStudyDate = `-- name: ReportFirstStudyDate :one
SELECT COALESCE(min((m.first_learned_at AT TIME ZONE 'Asia/Shanghai')::date), '1970-01-01'::date)::date AS first_date
FROM mastery_records m
WHERE m.child_id = $1 AND m.first_learned_at IS NOT NULL
`

// 第一个学习日（对齐用的起点）
func (q *Queries) ReportFirstStudyDate(ctx context.Context, childID uuid.UUID) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, reportFirstStudyDate, childID)
	var first_date pgtype.Date
	err := row.Scan(&first_date)
	return first_date, err
}

const reportKPDailyAccuracy = `-- name: ReportKPDailyAccuracy :many
SELECT
    a.kp_id,
    (a.created_at AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    count(*)::bigint                                    AS attempts,
    count(*) FILTER (WHERE a.is_correct)::bigint        AS correct_count
FROM answer_logs a
WHERE a.child_id = $1
  AND a.created_at >= $2
  AND ($3::text = '' OR a.subject_code = $3::text)
GROUP BY a.kp_id, 2
ORDER BY a.kp_id, 2
`

type ReportKPDailyAccuracyParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	SinceTs     pgtype.Timestamptz `json:"since_ts"`
	SubjectCode string             `json:"subject_code"`
}

type ReportKPDailyAccuracyRow struct {
	KpID         uuid.UUID   `json:"kp_id"`
	StatDate     pgtype.Date `json:"stat_date"`
	Attempts     int64       `json:"attempts"`
	CorrectCount int64       `json:"correct_count"`
}

// 逐日逐知识点的正确率（最近 N 天），service 用它判「连续 3 天低正确率」
func (q *Queries) ReportKPDailyAccuracy(ctx context.Context, arg ReportKPDailyAccuracyParams) ([]ReportKPDailyAccuracyRow, error) {
	rows, err := q.db.Query(ctx, reportKPDailyAccuracy, arg.ChildID, arg.SinceTs, arg.SubjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportKPDailyAccuracyRow{}
	for rows.Next() {
		var i ReportKPDailyAccuracyRow
		if err := rows.Scan(
			&i.KpID,
			&i.StatDate,
			&i.Attempts,
			&i.CorrectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportLastStudyDate = `-- name: ReportLastStudyDate :one
SELECT COALESCE(max(a.created_at), to_timestamp(0))::timestamptz AS last_at
FROM answer_logs a
WHERE a.child_id = $1
  AND a.subject_code = $2
`

type ReportLastStudyDateParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
}

// 某学科最近一次学习日期（建议规则 2：连续 5 天未学）
func (q *Queries) ReportLastStudyDate(ctx context.Context, arg ReportLastStudyDateParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, reportLastStudyDate, arg.ChildID, arg.SubjectCode)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}

const reportMasteryTotals = `-- name: ReportMasteryTotals :one


SELECT
    count(*)::bigint                                          AS mastered_total,
    count(*) FILTER (WHERE k.subject_code = 'chinese')::bigint AS mastered_chinese,
    count(*) FILTER (WHERE k.subject_code = 'math')::bigint    AS mastered_math,
    count(*) FILTER (WHERE k.subject_code = 'english')::bigint AS mastered_english,
    COALESCE(sum(m.attempts_to_master), 0)::bigint             AS attempts_to_master_sum
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1 AND m.level >= 3
`

type ReportMasteryTotalsRow struct {
	MasteredTotal       int64 `json:"mastered_total"`
	MasteredChinese     int64 `json:"mastered_chinese"`
	MasteredMath        int64 `json:"mastered_math"`
	MasteredEnglish     int64 `json:"mastered_english"`
	AttemptsToMasterSum int64 `json:"attempts_to_master_sum"`
}

// 报表 / 成就 / 日汇总的查询。
//
// 约定：
//  1. 「学习日」按 Asia/Shanghai 切分（M3 的 daily_stats.stat_date 就是用本机 +08 时区的
//     startOfDay 算的，两边一致才不会出现同一晚跨天的行被算到两天）。
//  2. 报表模块会直接 JOIN knowledge_points 取学科/阶段 —— 读报表天然需要多表聚合，
//     走 content.Service 反而要拆成 N 次查询并自带 N+1，这里按「读模型」处理。
//  3. 不排名、不做负向判定：SQL 只出事实，措辞在 service 层统一。
//
// ---------------------------------------------------------------- 总览
func (q *Queries) ReportMasteryTotals(ctx context.Context, childID uuid.UUID) (ReportMasteryTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportMasteryTotals, childID)
	var i ReportMasteryTotalsRow
	err := row.Scan(
		&i.MasteredTotal,
		&i.MasteredChinese,
		&i.MasteredMath,
		&i.MasteredEnglish,
		&i.AttemptsToMasterSum,
	)
	return i, err
}

const reportPaceSeries = `-- name: ReportPaceSeries :many

SELECT stat_date, subject_code, planned_new, actual_new, repeat_count,
       cum_planned, cum_actual, deviation_days
FROM daily_stats
WHERE child_id = $1
  AND stat_date >= $2
  AND stat_date <= $3
  AND subject_code <> ''
  AND ($4::text = '' OR subject_code = $4::text)
ORDER BY stat_date, subject_code
`

type ReportPaceSeriesParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	SubjectCode string      `json:"subject_code"`
}

type ReportPaceSeriesRow struct {
	StatDate      pgtype.Date `json:"stat_date"`
	SubjectCode   string      `json:"subject_code"`
	PlannedNew    int32       `json:"planned_new"`
	ActualNew     int32       `json:"actual_new"`
	RepeatCount   int32       `json:"repeat_count"`
	CumPlanned    int32       `json:"cum_planned"`
	CumActual     int32       `json:"cum_actual"`
	DeviationDays float64     `json:"deviation_days"`
}

// ---------------------------------------------------------------- 节奏与效率（§4.9）
// 逐日计划 vs 实际（分学科），pace 报表的双曲线数据源
func (q *Queries) ReportPaceSeries(ctx context.Context, arg ReportPaceSeriesParams) ([]ReportPaceSeriesRow, error) {
	rows, err := q.db.Query(ctx, reportPaceSeries,
		arg.ChildID,
		arg.FromDate,
		arg.ToDate,
		arg.SubjectCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPaceSeriesRow{}
	for rows.Next() {
		var i ReportPaceSeriesRow
		if err := rows.Scan(
			&i.StatDate,
			&i.SubjectCode,
			&i.PlannedNew,
			&i.ActualNew,
			&i.RepeatCount,
			&i.CumPlanned,
			&i.CumActual,
			&i.DeviationDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPlannedDateAtProgress = `-- name: ReportPlannedDateAtProgress :one
SELECT planned_date
FROM curriculum_plan
WHERE child_id = $1
  AND subject_code = $2
ORDER BY planned_day_index
OFFSET GREATEST($3::int - 1, 0)
LIMIT 1
`

type ReportPlannedDateAtProgressParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
	Progress    int32     `json:"progress"`
}

// 当前偏差：当日掌握的进度所对应的计划日期（工作日）。
// offset = 已掌握数 - 1，落在计划顺序上取那一天；service 再算 今天 - planned_date。
func (q *Queries) ReportPlannedDateAtProgress(ctx context.Context, arg ReportPlannedDateAtProgressParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, reportPlannedDateAtProgress, arg.ChildID, arg.SubjectCode, arg.Progress)
	var planned_date pgtype.Date
	err := row.Scan(&planned_date)
	return planned_date, err
}

const reportSessionTotals = `-- name: ReportSessionTotals :one
SELECT
    count(*)::bigint                                          AS session_count,
    count(*) FILTER (WHERE status = 'finished')::bigint        AS finished_count,
    COALESCE(avg(correct_count::numeric / NULLIF(answered_count, 0)), 0)::float8 AS avg_accuracy
FROM learning_sessions
WHERE child_id = $1
`

type ReportSessionTotalsRow struct {
	SessionCount  int64   `json:"session_count"`
	FinishedCount int64   `json:"finished_count"`
	AvgAccuracy   float64 `json:"avg_accuracy"`
}

func (q *Queries) ReportSessionTotals(ctx context.Context, childID uuid.UUID) (ReportSessionTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportSessionTotals, childID)
	var i ReportSessionTotalsRow
	err := row.Scan(&i.SessionCount, &i.FinishedCount, &i.AvgAccuracy)
	return i, err
}

const reportStageProgress = `-- name: ReportStageProgress :many
SELECT
    k.stage_code,
    COALESCE(count(DISTINCT k.id), 0)::bigint                              AS planned_total,
    COALESCE(count(DISTINCT k.id) FILTER (WHERE m.level >= 3), 0)::bigint  AS mastered
FROM knowledge_points k
LEFT JOIN mastery_records m ON m.kp_id = k.id AND m.child_id = $1
WHERE k.subject_code = $2
  AND k.status = 'published'
  AND k.stage_code IS NOT NULL
GROUP BY k.stage_code
ORDER BY k.stage_code
`

type ReportStageProgressParams struct {
	ChildID     uuid.UUID `json:"child_id"`
	SubjectCode string    `json:"subject_code"`
}

type ReportStageProgressRow struct {
	StageCode    pgtype.Text `json:"stage_code"`
	PlannedTotal int64       `json:"planned_total"`
	Mastered     int64       `json:"mastered"`
}

// 分阶段进度（成长树用）：该阶段的计划量 / 已掌握量
func (q *Queries) ReportStageProgress(ctx context.Context, arg ReportStageProgressParams) ([]ReportStageProgressRow, error) {
	rows, err := q.db.Query(ctx, reportStageProgress, arg.ChildID, arg.SubjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportStageProgressRow{}
	for rows.Next() {
		var i ReportStageProgressRow
		if err := rows.Scan(&i.StageCode, &i.PlannedTotal, &i.Mastered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSubjectProgress = `-- name: ReportSubjectProgress :many
SELECT
    s.code AS subject_code,
    s.name AS subject_name,
    COALESCE(mp.mastered, 0)::bigint AS mastered,
    COALESCE(pl.total, 0)::bigint    AS planned_total,
    COALESCE(dq.due, 0)::bigint      AS due
FROM subjects s
LEFT JOIN (
    SELECT k.subject_code, count(*) AS mastered
    FROM mastery_records m JOIN knowledge_points k ON k.id = m.kp_id
    WHERE m.child_id = $1 AND m.level >= 3
    GROUP BY k.subject_code
) mp ON mp.subject_code = s.code
LEFT JOIN (
    SELECT subject_code, count(*) AS total FROM curriculum_plan
    WHERE child_id = $1 GROUP BY subject_code
) pl ON pl.subject_code = s.code
LEFT JOIN (
    SELECT k.subject_code, count(*) AS due
    FROM mastery_records m JOIN knowledge_points k ON k.id = m.kp_id
    WHERE m.child_id = $1 AND m.level > 0 AND m.next_review_at <= $2
    GROUP BY k.subject_code
) dq ON dq.subject_code = s.code
ORDER BY s.sort_order
`

type ReportSubjectProgressParams struct {
	ChildID uuid.UUID          `json:"child_id"`
	NowTs   pgtype.Timestamptz `json:"now_ts"`
}

type ReportSubjectProgressRow struct {
	SubjectCode  string `json:"subject_code"`
	SubjectName  string `json:"subject_name"`
	Mastered     int64  `json:"mastered"`
	PlannedTotal int64  `json:"planned_total"`
	Due          int64  `json:"due"`
}

// 分学科进度：已掌握 / 计划总量 / 待复习
func (q *Queries) ReportSubjectProgress(ctx context.Context, arg ReportSubjectProgressParams) ([]ReportSubjectProgressRow, error) {
	rows, err := q.db.Query(ctx, reportSubjectProgress, arg.ChildID, arg.NowTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSubjectProgressRow{}
	for rows.Next() {
		var i ReportSubjectProgressRow
		if err := rows.Scan(
			&i.SubjectCode,
			&i.SubjectName,
			&i.Mastered,
			&i.PlannedTotal,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTotals = `-- name: ReportTotals :one
SELECT
    COALESCE(sum(duration_sec), 0)::bigint   AS duration_sec,
    COALESCE(sum(question_count), 0)::bigint AS question_count,
    COALESCE(sum(correct_count), 0)::bigint  AS correct_count,
    COALESCE(sum(star_count), 0)::bigint     AS star_count,
    count(*) FILTER (WHERE question_count > 0)::bigint AS active_days
FROM daily_stats
WHERE child_id = $1 AND subject_code = ''
`

type ReportTotalsRow struct {
	DurationSec   int64 `json:"duration_sec"`
	QuestionCount int64 `json:"question_count"`
	CorrectCount  int64 `json:"correct_count"`
	StarCount     int64 `json:"star_count"`
	ActiveDays    int64 `json:"active_days"`
}

func (q *Queries) ReportTotals(ctx context.Context, childID uuid.UUID) (ReportTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportTotals, childID)
	var i ReportTotalsRow
	err := row.Scan(
		&i.DurationSec,
		&i.QuestionCount,
		&i.CorrectCount,
		&i.StarCount,
		&i.ActiveDays,
	)
	return i, err
}

const reportWeakKPs = `-- name: ReportWeakKPs :many

SELECT
    k.id AS kp_id, k.code, k.name, k.stage_code, k.subject_code,
    count(*)::bigint                            AS attempts,
    count(*) FILTER (WHERE a.is_correct)::bigint AS correct_count,
    COALESCE(max(a.created_at), to_timestamp(0))::timestamptz AS last_answered_at
FROM answer_logs a
JOIN knowledge_points k ON k.id = a.kp_id
LEFT JOIN mastery_records m ON m.child_id = a.child_id AND m.kp_id = a.kp_id
WHERE a.child_id = $1
  AND a.created_at >= $2
  AND ($3::text = '' OR a.subject_code = $3::text)
  AND COALESCE(m.level, 0) < 3
GROUP BY k.id, k.code, k.name, k.stage_code, k.subject_code
HAVING count(*) FILTER (WHERE NOT a.is_correct) > 0
ORDER BY (count(*) FILTER (WHERE NOT a.is_correct))::bigint DESC, count(*) DESC
LIMIT $4
`

type ReportWeakKPsParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	SinceTs     pgtype.Timestamptz `json:"since_ts"`
	SubjectCode string             `json:"subject_code"`
	Lim         int32              `json:"lim"`
}

type ReportWeakKPsRow struct {
	KpID           uuid.UUID          `json:"kp_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	StageCode      pgtype.Text        `json:"stage_code"`
	SubjectCode    string             `json:"subject_code"`
	Attempts       int64              `json:"attempts"`
	CorrectCount   int64              `json:"correct_count"`
	LastAnsweredAt pgtype.Timestamptz `json:"last_answered_at"`
}

// ---------------------------------------------------------------- 薄弱项（建议规则 1）
// 某学科最近 N 天里「掌握度还不到 3 且答错过」的知识点，按错误率排序（TopN）
func (q *Queries) ReportWeakKPs(ctx context.Context, arg ReportWeakKPsParams) ([]ReportWeakKPsRow, error) {
	rows, err := q.db.Query(ctx, reportWeakKPs,
		arg.ChildID,
		arg.SinceTs,
		arg.SubjectCode,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportWeakKPsRow{}
	for rows.Next() {
		var i ReportWeakKPsRow
		if err := rows.Scan(
			&i.KpID,
			&i.Code,
			&i.Name,
			&i.StageCode,
			&i.SubjectCode,
			&i.Attempts,
			&i.CorrectCount,
			&i.LastAnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportWeakQuestionTypes = `-- name: ReportWeakQuestionTypes :many
SELECT
    a.question_type,
    count(*)::bigint                             AS attempts,
    count(*) FILTER (WHERE NOT a.is_correct)::bigint AS wrong_count,
    (count(*) FILTER (WHERE NOT a.is_correct))::float8 / count(*)::float8 AS wrong_rate
FROM answer_logs a
WHERE a.child_id = $1
  AND a.created_at >= $2
  AND a.question_type <> ''
GROUP BY a.question_type
HAVING count(*) FILTER (WHERE NOT a.is_correct) > 0
ORDER BY (count(*) FILTER (WHERE NOT a.is_correct))::bigint DESC, count(*) DESC
LIMIT $3
`

type ReportWeakQuestionTypesParams struct {
	ChildID uuid.UUID          `json:"child_id"`
	SinceTs pgtype.Timestamptz `json:"since_ts"`
	Lim     int32              `json:"lim"`
}

type ReportWeakQuestionTypesRow struct {
	QuestionType string `json:"question_type"`
	Attempts     int64  `json:"attempts"`
	WrongCount   int64  `json:"wrong_count"`
	WrongRate    int32  `json:"wrong_rate"`
}

// 薄弱题型 TopN（§4.7 数据源）
func (q *Queries) ReportWeakQuestionTypes(ctx context.Context, arg ReportWeakQuestionTypesParams) ([]ReportWeakQuestionTypesRow, error) {
	rows, err := q.db.Query(ctx, reportWeakQuestionTypes, arg.ChildID, arg.SinceTs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportWeakQuestionTypesRow{}
	for rows.Next() {
		var i ReportWeakQuestionTypesRow
		if err := rows.Scan(
			&i.QuestionType,
			&i.Attempts,
			&i.WrongCount,
			&i.WrongRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportWeeklyEfficiency = `-- name: ReportWeeklyEfficiency :many
SELECT
    date_trunc('week', m.mastered_at AT TIME ZONE 'Asia/Shanghai')::date AS week_start,
    count(*)::bigint                                 AS mastered_count,
    COALESCE(sum(m.attempts_to_master), 0)::bigint   AS attempts_sum,
    COALESCE(avg(m.attempts_to_master), 0)::float8   AS attempts_per_mastery
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND m.mastered_at IS NOT NULL
  AND m.mastered_at >= $2
  AND ($3::text = '' OR k.subject_code = $3::text)
GROUP BY 1
ORDER BY 1
`

type ReportWeeklyEfficiencyParams struct {
	ChildID     uuid.UUID          `json:"child_id"`
	SinceTs     pgtype.Timestamptz `json:"since_ts"`
	SubjectCode string             `json:"subject_code"`
}

type ReportWeeklyEfficiencyRow struct {
	WeekStart          pgtype.Date `json:"week_start"`
	MasteredCount      int64       `json:"mastered_count"`
	AttemptsSum        int64       `json:"attempts_sum"`
	AttemptsPerMastery float64     `json:"attempts_per_mastery"`
}

// 效率趋势：按自然周统计「掌握数 / 总作答数 / 正确率」（近 N 周滚动）
func (q *Queries) ReportWeeklyEfficiency(ctx context.Context, arg ReportWeeklyEfficiencyParams) ([]ReportWeeklyEfficiencyRow, error) {
	rows, err := q.db.Query(ctx, reportWeeklyEfficiency, arg.ChildID, arg.SinceTs, arg.SubjectCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportWeeklyEfficiencyRow{}
	for rows.Next() {
		var i ReportWeeklyEfficiencyRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.MasteredCount,
			&i.AttemptsSum,
			&i.AttemptsPerMastery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupCumMastered = `-- name: RollupCumMastered :one
SELECT count(*)::bigint
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND k.subject_code = $2
  AND m.mastered_at IS NOT NULL
  AND (m.mastered_at AT TIME ZONE 'Asia/Shanghai')::date <= $3::date
`

type RollupCumMasteredParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

func (q *Queries) RollupCumMastered(ctx context.Context, arg RollupCumMasteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupCumMastered, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const rollupCumPlanned = `-- name: RollupCumPlanned :one
SELECT count(*)::bigint
FROM curriculum_plan
WHERE child_id = $1
  AND subject_code = $2
  AND planned_date <= $3::date
`

type RollupCumPlannedParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

func (q *Queries) RollupCumPlanned(ctx context.Context, arg RollupCumPlannedParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupCumPlanned, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const rollupDailyAnswers = `-- name: RollupDailyAnswers :one
SELECT
    count(*)::bigint                            AS attempts,
    count(*) FILTER (WHERE is_correct)::bigint   AS correct_count
FROM answer_logs
WHERE child_id = $1
  AND subject_code = $2
  AND (created_at AT TIME ZONE 'Asia/Shanghai')::date = $3::date
`

type RollupDailyAnswersParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

type RollupDailyAnswersRow struct {
	Attempts     int64 `json:"attempts"`
	CorrectCount int64 `json:"correct_count"`
}

// 当日该学科的作答与正确数（判达标用，避免与 M3 的增量口径互相打架）
func (q *Queries) RollupDailyAnswers(ctx context.Context, arg RollupDailyAnswersParams) (RollupDailyAnswersRow, error) {
	row := q.db.QueryRow(ctx, rollupDailyAnswers, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var i RollupDailyAnswersRow
	err := row.Scan(&i.Attempts, &i.CorrectCount)
	return i, err
}

const rollupDailyMastered = `-- name: RollupDailyMastered :one
SELECT count(*)::bigint
FROM mastery_records m
JOIN knowledge_points k ON k.id = m.kp_id
WHERE m.child_id = $1
  AND k.subject_code = $2
  AND m.mastered_at IS NOT NULL
  AND (m.mastered_at AT TIME ZONE 'Asia/Shanghai')::date = $3::date
`

type RollupDailyMasteredParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

func (q *Queries) RollupDailyMastered(ctx context.Context, arg RollupDailyMasteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupDailyMastered, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const rollupParentConfirmed = `-- name: RollupParentConfirmed :one
SELECT EXISTS (
    SELECT 1 FROM learning_sessions
    WHERE child_id = $1
      AND completed_by IN ('parent', 'mixed')
      AND (COALESCE(ended_at, started_at) AT TIME ZONE 'Asia/Shanghai')::date = $2::date
)::boolean AS confirmed
`

type RollupParentConfirmedParams struct {
	ChildID  uuid.UUID   `json:"child_id"`
	StatDate pgtype.Date `json:"stat_date"`
}

// 当日是否有家长确认（completed_by 为 parent / mixed 即视为家长参与过确认）
func (q *Queries) RollupParentConfirmed(ctx context.Context, arg RollupParentConfirmedParams) (bool, error) {
	row := q.db.QueryRow(ctx, rollupParentConfirmed, arg.ChildID, arg.StatDate)
	var confirmed bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const rollupPlannedForDate = `-- name: RollupPlannedForDate :one
SELECT count(*)::bigint
FROM curriculum_plan
WHERE child_id = $1
  AND subject_code = $2
  AND planned_date = $3::date
`

type RollupPlannedForDateParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

func (q *Queries) RollupPlannedForDate(ctx context.Context, arg RollupPlannedForDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupPlannedForDate, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const rollupRepeatCount = `-- name: RollupRepeatCount :one
SELECT count(*)::bigint
FROM answer_logs a
JOIN mastery_records m ON m.child_id = a.child_id AND m.kp_id = a.kp_id
WHERE a.child_id = $1
  AND a.subject_code = $2
  AND (a.created_at AT TIME ZONE 'Asia/Shanghai')::date = $3::date
  AND m.first_learned_at IS NOT NULL
  AND (m.first_learned_at AT TIME ZONE 'Asia/Shanghai')::date < $3::date
`

type RollupRepeatCountParams struct {
	ChildID     uuid.UUID   `json:"child_id"`
	SubjectCode string      `json:"subject_code"`
	StatDate    pgtype.Date `json:"stat_date"`
}

// 当日「重复练习」量：当天作答的题里，知识点在当天之前就已经学过（首学日 < 当天）
func (q *Queries) RollupRepeatCount(ctx context.Context, arg RollupRepeatCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollupRepeatCount, arg.ChildID, arg.SubjectCode, arg.StatDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertDailyRollup = `-- name: UpsertDailyRollup :exec
INSERT INTO daily_stats (
    child_id, stat_date, subject_code, new_mastered, planned_new, actual_new, repeat_count,
    cum_planned, cum_actual, deviation_days, passed, parent_confirmed, updated_at)
VALUES (
    $1, $2::date, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, now())
ON CONFLICT (child_id, stat_date, subject_code) DO UPDATE SET
    new_mastered     = EXCLUDED.new_mastered,
    planned_new      = EXCLUDED.planned_new,
    actual_new       = EXCLUDED.actual_new,
    repeat_count     = EXCLUDED.repeat_count,
    cum_planned      = EXCLUDED.cum_planned,
    cum_actual       = EXCLUDED.cum_actual,
    deviation_days   = EXCLUDED.deviation_days,
    passed           = EXCLUDED.passed,
    parent_confirmed = EXCLUDED.parent_confirmed,
    updated_at       = now()
`

type UpsertDailyRollupParams struct {
	ChildID         uuid.UUID   `json:"child_id"`
	StatDate        pgtype.Date `json:"stat_date"`
	SubjectCode     string      `json:"subject_code"`
	NewMastered     int32       `json:"new_mastered"`
	PlannedNew      int32       `json:"planned_new"`
	ActualNew       int32       `json:"actual_new"`
	RepeatCount     int32       `json:"repeat_count"`
	CumPlanned      int32       `json:"cum_planned"`
	CumActual       int32       `json:"cum_actual"`
	DeviationDays   float64     `json:"deviation_days"`
	Passed          bool        `json:"passed"`
	ParentConfirmed bool        `json:"parent_confirmed"`
}

// 写回汇总行：只覆盖「计划/节奏/达标」这几列，时长与题量仍以会话增量为准。
func (q *Queries) UpsertDailyRollup(ctx context.Context, arg UpsertDailyRollupParams) error {
	_, err := q.db.Exec(ctx, upsertDailyRollup,
		arg.ChildID,
		arg.StatDate,
		arg.SubjectCode,
		arg.NewMastered,
		arg.PlannedNew,
		arg.ActualNew,
		arg.RepeatCount,
		arg.CumPlanned,
		arg.CumActual,
		arg.DeviationDays,
		arg.Passed,
		arg.ParentConfirmed,
	)
	return err
}

const upsertParentSettings = `-- name: UpsertParentSettings :one
INSERT INTO parent_settings (
    parent_id, daily_limit_min, session_limit_min, rest_interval_min,
    require_parent_confirm, pace_mode, compare_children, updated_at)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, now())
ON CONFLICT (parent_id) DO UPDATE SET
    daily_limit_min        = EXCLUDED.daily_limit_min,
    session_limit_min      = EXCLUDED.session_limit_min,
    rest_interval_min      = EXCLUDED.rest_interval_min,
    require_parent_confirm = EXCLUDED.require_parent_confirm,
    pace_mode              = EXCLUDED.pace_mode,
    compare_children       = EXCLUDED.compare_children,
    updated_at             = now()
RETURNING parent_id, daily_limit_min, session_limit_min, rest_interval_min,
          require_parent_confirm, pace_mode, compare_children
`

type UpsertParentSettingsParams struct {
	ParentID             uuid.UUID `json:"parent_id"`
	DailyLimitMin        int32     `json:"daily_limit_min"`
	SessionLimitMin      int32     `json:"session_limit_min"`
	RestIntervalMin      int32     `json:"rest_interval_min"`
	RequireParentConfirm bool      `json:"require_parent_confirm"`
	PaceMode             string    `json:"pace_mode"`
	CompareChildren      bool      `json:"compare_children"`
}

type UpsertParentSettingsRow struct {
	ParentID             uuid.UUID `json:"parent_id"`
	DailyLimitMin        int32     `json:"daily_limit_min"`
	SessionLimitMin      int32     `json:"session_limit_min"`
	RestIntervalMin      int32     `json:"rest_interval_min"`
	RequireParentConfirm bool      `json:"require_parent_confirm"`
	PaceMode             string    `json:"pace_mode"`
	CompareChildren      bool      `json:"compare_children"`
}

func (q *Queries) UpsertParentSettings(ctx context.Context, arg UpsertParentSettingsParams) (UpsertParentSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertParentSettings,
		arg.ParentID,
		arg.DailyLimitMin,
		arg.SessionLimitMin,
		arg.RestIntervalMin,
		arg.RequireParentConfirm,
		arg.PaceMode,
		arg.CompareChildren,
	)
	var i UpsertParentSettingsRow
	err := row.Scan(
		&i.ParentID,
		&i.DailyLimitMin,
		&i.SessionLimitMin,
		&i.RestIntervalMin,
		&i.RequireParentConfirm,
		&i.PaceMode,
		&i.CompareChildren,
	)
	return i, err
}
